In [1]:
out_dir = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/avg_maps/gm/normal'

# 01 - Get Datasets


**Data will be Imported from a CSV which is expected to be in this format**
- sub column contents MUST match the names of the neuroimaging files above. 
    - ID column 
```
+-----+----------------------------+--------------+--------------+--------------+
| sub | Nifti_File_Path            | Indep. Var.  | Covariate_N  | Dataset      |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 1            |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 1            |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 2            |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3            |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

In [2]:
input_csv_path = '/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/metadata/cleaned_information/master.csv'
sheet=None

In [3]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
cal_palm = CalvinStatsmodelsPalm(input_csv_path=input_csv_path, output_dir=out_dir, sheet=sheet)
data_df = cal_palm.read_and_display_data()
display(data_df)

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed,spatial_correlation_CSF_AD,cosine_CSF_AD,cosine_CSF_MCI,cosine_CSF_CN
0,0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.592110,-18245.868460,-32777.023890,-23248.955500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.207187,0.227202,0.236543,0.225010
1,1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.977170,-6191.852471,-13476.493390,-4562.384254,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.064707,-0.009701,0.010196,0.152369
2,2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.367040,-33934.639930,-32128.021820,-7651.536038,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.114274,0.187858,0.167963,0.209394
3,3,002_S_0619,-35472.21632,-23876.106190,-1947.061673,-51088.102680,-81475.108430,-66818.857830,-72864.628840,-30069.234640,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.485236,0.580121,0.562639,0.325657
4,4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.083970,-48808.714580,-31102.255680,-7164.119248,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.252730,0.315671,0.301218,0.345948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383,1383,941_S_4365,-38529.96216,-15404.929680,-662.636580,-45763.001790,-51966.135180,-50434.470830,-48981.572530,-9171.789970,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.310430,0.430964,0.401940,0.254941
1384,1384,941_S_4376,-17949.11453,-104.528538,-236.251734,-30861.230910,-12256.220060,-26738.830580,-20657.277210,-21140.712780,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.086340,0.124990,0.108221,0.094331
1385,1385,941_S_4377,-15992.36193,8601.241440,-63.774856,-17403.780770,-5480.603967,-8570.005333,-6582.358081,8848.744873,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,-0.049510,-0.049247,0.042858,0.033507
1386,1386,941_S_4420,-16826.37025,-551.877244,-240.304833,-19856.342990,-43372.373360,-24995.432550,-31441.476020,-5076.530307,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.135876,0.188406,0.184488,0.072262
1387,1387,941_S_4764,-29967.55872,-4994.645463,-611.921947,-31815.427780,-48597.166250,-30940.654970,-37860.577210,-16533.750280,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.379000,0.481642,0.465129,0.262801

**Handle NANs**
- Set drop_nans=True is you would like to remove NaNs from data
- Provide a column name or a list of column names to remove NaNs from

In [4]:
drop_list = ['fluid_atrophy_path_smoothed', 'DX_BASELINE', 'Visual_Subcortex']

In [5]:
data_df = cal_palm.drop_nans_from_columns(columns_to_drop_from=drop_list)
display(data_df)

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed,spatial_correlation_CSF_AD,cosine_CSF_AD,cosine_CSF_MCI,cosine_CSF_CN
0,0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.592110,-18245.868460,-32777.02389,-23248.955500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.207187,0.227202,0.236543,0.225010
1,1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.977170,-6191.852471,-13476.49339,-4562.384254,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.064707,-0.009701,0.010196,0.152369
2,2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.367040,-33934.639930,-32128.02182,-7651.536038,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.114274,0.187858,0.167963,0.209394
4,4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.083970,-48808.714580,-31102.25568,-7164.119248,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.252730,0.315671,0.301218,0.345948
5,5,002_S_0729,-14931.99589,9351.074758,-392.045941,-16190.164180,6146.821509,-3848.640986,-14880.99255,7723.777233,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,-0.027329,-0.089672,-0.056970,0.103892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1326,1326,141_S_0790,-18274.00017,3282.586207,-299.272569,-16010.103010,-30354.498030,-23638.487500,-22186.27001,17343.782780,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.256338,0.319196,0.308349,0.118053
1329,1329,141_S_0852,-11199.97032,4181.203209,-1557.320283,-20065.213510,-24016.923460,-26920.294260,-34367.55586,9397.333523,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.189900,0.241084,0.194341,0.116859
1338,1338,141_S_1137,-23089.70453,-10745.059490,-1129.400838,-41824.703730,-36131.115530,-33677.468890,-43382.10995,-6729.084250,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.486403,0.572129,0.500387,0.348046
1339,1339,141_S_1152,-13628.75801,-6510.956805,-679.958590,-20290.388240,-4794.264065,-13936.061260,-22084.88688,23967.575890,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.286714,0.319137,0.311405,0.226893
1372,1372,941_S_1202,-26352.60488,-735.110333,-561.225070,-9934.943656,-33858.185030,-19699.733350,-23136.85671,-43373.920500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.117192,0.163062,0.192889,0.151485

In [6]:
# dataset_counts = data_df['Dataset'].value_counts()
# print(dataset_counts)

**Drop Row Based on Value of Column**

Define the column, condition, and value for dropping rows
- column = 'your_column_name'
- condition = 'above'  # Options: 'equal', 'above', 'below'

In [7]:
column = 'DX_BASELINE'
condition = 'not'
value = 'Normal'

In [8]:
data_df, other_df = cal_palm.drop_rows_based_on_value(column, condition, value)
data_df

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed,spatial_correlation_CSF_AD,cosine_CSF_AD,cosine_CSF_MCI,cosine_CSF_CN
0,0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.592110,-18245.868460,-32777.023890,-23248.955500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.207187,0.227202,0.236543,0.225010
1,1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.977170,-6191.852471,-13476.493390,-4562.384254,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.064707,-0.009701,0.010196,0.152369
2,2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.367040,-33934.639930,-32128.021820,-7651.536038,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.114274,0.187858,0.167963,0.209394
4,4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.083970,-48808.714580,-31102.255680,-7164.119248,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.252730,0.315671,0.301218,0.345948
14,14,002_S_1261,-20889.20741,5763.099978,-344.618493,-24094.153150,-3977.559440,-20346.426880,-23645.524910,-17081.950920,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.068222,0.074013,0.087542,0.179251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,727,062_S_0768,-66793.98746,-11547.953600,-968.723401,-39934.426060,-69406.899110,-54958.808240,-65424.482230,-31973.584050,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.278122,0.381651,0.318815,0.293810
893,893,094_S_0526,-11075.24340,2775.952022,-73.997417,-5151.837078,-5290.510920,-11667.592330,-8750.587788,34177.185970,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,-0.007825,-0.053382,-0.043504,0.094108
994,994,114_S_0173,-27034.47840,-6473.176667,-475.445981,-30531.736590,-44894.305790,-40722.428880,-44695.144200,-22284.818640,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.259344,0.344522,0.320487,0.276656
1055,1055,123_S_0298,-10793.59807,6266.267418,-369.291164,-16246.287070,-5452.212266,-20650.857670,-16681.070900,-12162.622060,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,-0.110750,-0.163326,-0.131523,0.012352
1372,1372,941_S_1202,-26352.60488,-735.110333,-561.225070,-9934.943656,-33858.185030,-19699.733350,-23136.856710,-43373.920500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.117192,0.163062,0.192889,0.151485

In [9]:
data_df.columns

Index(['Unnamed__0', 'subid', 'CSF_Cerebellum', 'CSF_Subcortex', 'CSF_MTL',
       'CSF_Occipital', 'CSF_Frontal', 'CSF_Parietal', 'CSF_Temporal',
       'GM_Cerebellum', 'GM_Subcortex', 'GM_MTL', 'GM_Occipital', 'GM_Frontal',
       'GM_Parietal', 'GM_Temporal', 'WM_Cerebellum', 'WM_Subcortex', 'WM_MTL',
       'WM_Occipital', 'WM_Frontal', 'WM_Parietal', 'WM_Temporal',
       'Visual_Frontal', 'Visual_Parietal', 'Visual_Occipital',
       'Visual_Temporal', 'Visual_Cerebellum', 'Visual_Subcortex',
       'Visual_MTL', 'Cohort', 'Diagnosis', 'Sex', 'Age', 'Cohort_1',
       'CTh_Cerebellum', 'CTh_MTL', 'CTh_Occipital', 'CTh_Frontal',
       'CTh_Parietal', 'CTh_Temporal', 'CTh_Subcortex', 'Q4', 'TOTAL11',
       'TOTALMOD', 'DX_BASELINE', 'DX_M12', 'wm_atrophy_path',
       'gm_atrophy_path', 'fluid_atrophy_path', 'composite_atrophy_path',
       'wm_atrophy_path_smoothed', 'gm_atrophy_path_smoothed',
       'fluid_atrophy_path_smoothed', 'composite_atrophy_path_smoothed',
       'spatial_correlation_CSF_AD', 'cosine_CSF_AD', 'cosine_CSF_MCI',
       'cosine_CSF_CN'],
      dtype='object')

In [10]:
# data_df = data_df.drop_duplicates(subset='PMID')
display(data_df)

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed,spatial_correlation_CSF_AD,cosine_CSF_AD,cosine_CSF_MCI,cosine_CSF_CN
0,0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.592110,-18245.868460,-32777.023890,-23248.955500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.207187,0.227202,0.236543,0.225010
1,1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.977170,-6191.852471,-13476.493390,-4562.384254,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.064707,-0.009701,0.010196,0.152369
2,2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.367040,-33934.639930,-32128.021820,-7651.536038,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.114274,0.187858,0.167963,0.209394
4,4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.083970,-48808.714580,-31102.255680,-7164.119248,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.252730,0.315671,0.301218,0.345948
14,14,002_S_1261,-20889.20741,5763.099978,-344.618493,-24094.153150,-3977.559440,-20346.426880,-23645.524910,-17081.950920,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.068222,0.074013,0.087542,0.179251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,727,062_S_0768,-66793.98746,-11547.953600,-968.723401,-39934.426060,-69406.899110,-54958.808240,-65424.482230,-31973.584050,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.278122,0.381651,0.318815,0.293810
893,893,094_S_0526,-11075.24340,2775.952022,-73.997417,-5151.837078,-5290.510920,-11667.592330,-8750.587788,34177.185970,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,-0.007825,-0.053382,-0.043504,0.094108
994,994,114_S_0173,-27034.47840,-6473.176667,-475.445981,-30531.736590,-44894.305790,-40722.428880,-44695.144200,-22284.818640,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.259344,0.344522,0.320487,0.276656
1055,1055,123_S_0298,-10793.59807,6266.267418,-369.291164,-16246.287070,-5452.212266,-20650.857670,-16681.070900,-12162.622060,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,-0.110750,-0.163326,-0.131523,0.012352
1372,1372,941_S_1202,-26352.60488,-735.110333,-561.225070,-9934.943656,-33858.185030,-19699.733350,-23136.856710,-43373.920500,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,0.117192,0.163062,0.192889,0.151485

# 02 - Import the Data into DataFrames, Control them, and Save them

In [11]:
# for idx, row in data_df.iterrows():
#     data_df.loc[idx, 'dataset'] = f"meta_analysis"

In [12]:
dataset_col = 'normal'
nifti_path_col = 'gm_atrophy_path_smoothed'
indep_var_col = 'DX_BASELINE'
covariate_cols = []

Prepare the data
- save the path to the JSON file created in your out_dir. This will be the basis of your further analyses

In [13]:
mask_path = '/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/resources/MNI152_T1_2mm_brain_mask.nii'

In [14]:
from calvin_utils.neuroimaging_utils.ccm_utils.nifti_utils import DatasetNiftiImporter
data_importer = DatasetNiftiImporter(df=data_df, dataset_col=dataset_col, nifti_col=nifti_path_col, 
                                     indep_var_col=indep_var_col, covariate_cols=covariate_cols, 
                                     out_dir=out_dir, 
                                     mask_path=mask_path,
                                     regression_method=None,
                                     data_transform_method=None)
data_importer.package_data()

Importing dataset:  dataset

Importing niftis: 100%|██████████| 61/61 [00:03<00:00, 20.08it/s]

(61, 228483) (61, 1) (61, 1)
Dataset dictionary saved to: /Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/avg_maps/gm/normal/tmp/dataset_dict.json

'/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/avg_maps/gm/normal/tmp/dataset_dict.json'