# Run Any Kind of OLS Regression (ANOVA, GLM, Logit, etc.)

### Authors: Calvin Howard.

#### Last updated: May 5, 2024

Use this to run/test a statistical model (e.g., regression or T-tests) on a spreadsheet containing covariates and brain image (nii/gii) paths. 

Notes:
- For this to work, it must be installed onto wherever you want to run it. You must run:
```
> git clone https://github.com/Calvinwhow/Research.git
> cd into wherever you installed it. 
> pip install -e .
```
- To best use this notebook, you should be familar with GLM design and Contrast Matrix design. See this webpage to get started:
[FSL's GLM page](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/GLM)

# 00 - Import CSV with All Data
**The CSV is expected to be in this format**
- ID and absolute paths to niftis are critical
```
+-----+----------------------------+--------------+--------------+--------------+
| ID  | Nifti_File_Path            | Covariate_1  | Covariate_2  | Covariate_3  |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 3.4          |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 3.1          |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 3.5          |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3.2          |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

Prep Output Direction

In [37]:
# Specify where you want to save your results to
out_dir = "/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/_placeholder_/standardized-perm1000"

Import Data

In [38]:
# Specify the path to your CSV file containing NIFTI paths
input_csv_path = '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/optimized_master_list.csv'
sheet = None

In [39]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
# Instantiate the PalmPrepararation class
cal_palm = CalvinStatsmodelsPalm(input_csv_path=input_csv_path, output_dir=out_dir, sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection3Score,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs
0,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,3,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
1,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,4,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
2,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,5,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
3,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,6,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4760445,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-016,HA-01-016-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
176,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5075289,Ax_Butler_BRAVO_Brain_Only,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-035,HA-01-035-7301,SCA3,Ax_Butler_BRAVO_Brain_Only,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
177,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5623298,Mag_Images,0,NaN,HA-01-050,HA-01-050-7301,SCA3,Sag_T1_Pre,...,-2.0,0.0,0.0,-5.0,-5.0,-10.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
178,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5623298,AAHead_Scout,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-050,HA-01-050-7301,SCA3,Sag_T1_Pre,...,-2.0,0.0,0.0,-5.0,-5.0,-10.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
179,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6868827,_C_Ax_3D_VIBE_F_S_and_METS,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-074,HA-01-074-7301,SCA3,Ax_T1_pre,...,0.0,-2.0,0.0,-3.0,-6.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...

In [41]:
string = ""
for col in data_df.columns:
    string = string + "'" + col + "', "
print(string)

'paths', 'Nifti_File_Path', 'subid', 'session', 'selected', 'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type', 'used_synthsr', 'Gait', 'HeelToShinTestLeft', 'HeelToShinTestRight', 'FingerToNoseTestLeft', 'FingerToNoseTestRight', 'LimbAtaxia', 'Speech', 'Oculomotor', 'TotalBarsScore', 'delta_days_bars', 'delta_days_ccas_x', 'SematicFluencyRawS', 'SematicFluencyFailS', 'PhonemicFluencyRawS', 'PhonemicFluencyFailS', 'CategorySwitchRawS', 'CategorySwitchFailS', 'VerbalRegSum', 'DigitSpanForwardRawS', 'DigitSpanForwardFailS', 'DigitSpanBackwardRawS', 'DigitSpanBackwardFailS', 'CubeDrawRawS', 'CubeDrawFailS', 'VerbalRecallRawS', 'VerbalRecallFailS', 'SimiliarityPair1RawS', 'SimiliarityPair2RawS', 'SimiliarityPair3RawS', 'SimiliarityPair4RawS', 'SimiliarityRawS', 'SimiliarityFailS', 'GoNoGoRawS', 'GoNoGoFailS', 'AFFECTAssessments_Angryoraggress', 'AFFECTAssessments_Difficultywith', 'AFFECTAssessments_Emotionallylab', 'AFFECTAssessments_Expressesillog', 'AFFECTAssessments_Lacksempathyis', 'AFFECTAssessments_Showseasysenso', 'AffectRawS', 'AffectFailS', 'TotalCCASRawScore', 'TotalCCASFailScore', 'MemoryTotal', 'ExecutiveTotal', 'LanguageTotal', 'VisualTotal', 'AffectTotal', 'delta_days_ccas_y', 'Sec1ADifficultFocus', 'Sec1AEasilyDistracted', 'Sec1AOntheGo', 'Sec1AFeelsCompelled', 'Sec1AFeelsDriven', 'Sec1BWorries', 'Sec1BRepeats', 'Sec1BMentallyStuck', 'Sec1BCauseDistress', 'Sec2AActHastily', 'Sec2ARapidChanges', 'Sec2ACryingLaughing', 'Sec2AOverAnxious', 'Sec2BLackOfPleasure', 'Sec2BNegativeAttitude', 'Sec2BUneasyWithLife', 'Sec2BSadDepressed', 'Sec3ARepetitiveMovements', 'Sec3ASensoryExp', 'Sec3BSensitive', 'Sec3BOverwhelmed', 'Sec4ACommunicates', 'Sec4AConcerns', 'Sec4ASeesHearsThings', 'Sec4BTroubleUnderstand', 'Sec4BDistant', 'Sec4BIndifferent', 'Sec5AAngry', 'Sec5AUpset', 'Sec5AIntolerant', 'Sec5AArgumentative', 'Sec5Bimmature', 'Sec5BUnaware', 'Sec5BManner', 'Sec5BTrusting', 'ScoreCol1A', 'ScoreCol1B', 'ScoreCol2A', 'ScoreCol2B', 'ScoreCol3A', 'ScoreCol3B', 'ScoreCol4A', 'ScoreCol4B', 'ScoreCol5A', 'ScoreCol5B', 'TotalSection1Score', 'TotalSection2Score', 'TotalSection3Score', 'TotalSection4Score', 'TotalSection5Score', 'CNRSTotColAScore', 'CNRSTotColBScore', 'CNRSTotScore', 'roi_path', 'conn_path', 'dataset', 'oatgs',


# 01 - Preprocess Your Data

**Handle NANs**
- Set drop_nans=True is you would like to remove NaNs from data
- Provide a column name or a list of column names to remove NaNs from

In [9]:
data_df.columns

Index(['paths', 'Nifti_File_Path', 'subid', 'session', 'selected',
       'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type',
       ...
       'TotalSection3Score', 'TotalSection4Score', 'TotalSection5Score',
       'CNRSTotColAScore', 'CNRSTotColBScore', 'CNRSTotScore', 'roi_path',
       'conn_path', 'dataset', 'oatgs'],
      dtype='object', length=118)

In [10]:
for col in data_df.columns:
    print(col)

paths
Nifti_File_Path
subid
session
selected
selected_Nifti_File_Path
id
local_id
diagnosis
scan_type
used_synthsr
Gait
HeelToShinTestLeft
HeelToShinTestRight
FingerToNoseTestLeft
FingerToNoseTestRight
LimbAtaxia
Speech
Oculomotor
TotalBarsScore
delta_days_bars
delta_days_ccas_x
SematicFluencyRawS
SematicFluencyFailS
PhonemicFluencyRawS
PhonemicFluencyFailS
CategorySwitchRawS
CategorySwitchFailS
VerbalRegSum
DigitSpanForwardRawS
DigitSpanForwardFailS
DigitSpanBackwardRawS
DigitSpanBackwardFailS
CubeDrawRawS
CubeDrawFailS
VerbalRecallRawS
VerbalRecallFailS
SimiliarityPair1RawS
SimiliarityPair2RawS
SimiliarityPair3RawS
SimiliarityPair4RawS
SimiliarityRawS
SimiliarityFailS
GoNoGoRawS
GoNoGoFailS
AFFECTAssessments_Angryoraggress
AFFECTAssessments_Difficultywith
AFFECTAssessments_Emotionallylab
AFFECTAssessments_Expressesillog
AFFECTAssessments_Lacksempathyis
AFFECTAssessments_Showseasysenso
AffectRawS
AffectFailS
TotalCCASRawScore
TotalCCASFailScore
MemoryTotal
ExecutiveTotal
LanguageTotal
VisualTotal
AffectTotal
delta_days_ccas_y
Sec1ADifficultFocus
Sec1AEasilyDistracted
Sec1AOntheGo
Sec1AFeelsCompelled
Sec1AFeelsDriven
Sec1BWorries
Sec1BRepeats
Sec1BMentallyStuck
Sec1BCauseDistress
Sec2AActHastily
Sec2ARapidChanges
Sec2ACryingLaughing
Sec2AOverAnxious
Sec2BLackOfPleasure
Sec2BNegativeAttitude
Sec2BUneasyWithLife
Sec2BSadDepressed
Sec3ARepetitiveMovements
Sec3ASensoryExp
Sec3BSensitive
Sec3BOverwhelmed
Sec4ACommunicates
Sec4AConcerns
Sec4ASeesHearsThings
Sec4BTroubleUnderstand
Sec4BDistant
Sec4BIndifferent
Sec5AAngry
Sec5AUpset
Sec5AIntolerant
Sec5AArgumentative
Sec5Bimmature
Sec5BUnaware
Sec5BManner
Sec5BTrusting
ScoreCol1A
ScoreCol1B
ScoreCol2A
ScoreCol2B
ScoreCol3A
ScoreCol3B
ScoreCol4A
ScoreCol4B
ScoreCol5A
ScoreCol5B
TotalSection1Score
TotalSection2Score
TotalSection3Score
TotalSection4Score
TotalSection5Score
CNRSTotColAScore
CNRSTotColBScore
CNRSTotScore
roi_path
conn_path
dataset
oatgs

In [11]:
variable = "Gait"

In [12]:
out_dir = out_dir.replace("_placeholder", variable)

In [13]:
drop_list = ['selected_Nifti_File_Path', variable]

In [14]:
data_df = cal_palm.drop_nans_from_columns(columns_to_drop_from=drop_list)
data_df

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection3Score,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
7,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6930044,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
8,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1355923,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-103,HA-01-103-7301,SCA27B,T1_MPRAGE_SAG,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
13,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1539729,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
15,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16067027,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
24,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16721995,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
26,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,20508602,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
33,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2071224,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-099,HA-01-099-7301,SCA27B,15_Sag_T1_3D_MP_PR_Cor_MPR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
36,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2368336,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-002,HA-01-002-7301,SCA6,C__Cor_T1_3D,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
38,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2369031,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-091,HA-01-091-7301,SCA27B,MPR_Coronal_Ref___Revised_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
43,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,315616,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
45,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3241194,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-089,HA-01-089-7301,SCA27B,27_Sag_T1_3D_MP_mitigation,...,-4.0,0.0,-2.0,-7.0,-10.0,-17.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
52,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,43218874,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
54,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4392765,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-105,HA-01-105-7301,SCA27B,Sag_T1_3D_MPRAG_MPR_Ax_MPR,...,0.0,0.0,-3.0,-7.0,-1.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
61,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4401431,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-051,HA-01-051-7301,SCA6,Sag_T1_3D_MPRAG_mitigation,...,-1.0,-4.0,-4.0,-18.0,-16.0,-34.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
63,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4530107,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-010,HA-01-010-7301,SCA2,COR_MPR_PRE,...,0.0,-1.0,-1.0,-3.0,-9.0,-12.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
67,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4552969,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-019,HA-01-019-7301,SCA1,_MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
74,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4722004,C__Ax_3D_VIBE,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-006,HA-01-006-7301,SCA3,C__Cor_T1_FS,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
79,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4783569,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-015,HA-01-015-7301,SCA3,Post_t1_SAG_MPRAGE,...,-2.0,-6.0,-5.0,-11.0,-16.0,-27.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
84,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4792757,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-031,HA-01-031-7301,SCA1,AXIAL_MPRAGE_RECONS,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
85,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5180657,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-032,HA-01-032-7301,SCA6,501__T2_Sag_3D_Brain_VIEW,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
87,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5199392,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-076,HA-01-076-7301,SCA3,PRE_Cor_T1_3D_Bravo_MPR,...,-1.0,-4.0,-2.0,-12.0,-10.0,-22.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
89,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5390756,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-047,HA-01-047-7301,SCA6/8,6__Sag_T1,...,0.0,0.0,0.0,-3.0,-1.0,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
92,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5410367,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-034,HA-01-034-7301,SCA1,COR_MPRAGE_REFORM,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
94,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5709549,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-039,HA-01-039-7301,SCA3,3d_Sag_T1,...,-3.0,-3.0,-3.0,-10.0,-9.0,-19.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
95,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5737974,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-046,HA-01-046-7301,SCA3,T1_TSE_AXIAL_3MM,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
97,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5766687,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-087,HA-01-087-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
101,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5997510,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-093,HA-01-093-7301,SCA27B,MPR_Ob_Cor_A____1_0_th_1_0,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
110,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6038408,9,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-098,HA-01-098-7301,SCA27B,COR_T1_MPR,...,0.0,-4.0,-2.0,-9.0,-7.0,-16.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
111,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6227801,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-055,HA-01-055-7301,SCA2,PRE_SAG_3D_T1_MPR,...,-3.0,-1.0,-7.0,-9.0,-14.0,-23.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
116,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6241170,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-085,HA-01-085-7301,SCA27B,12_Post_3D_Ax_T1_BRAVO,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
117,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6350474,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-108,HA-01-108-7301,CANVAS,SAG_T1_FS_Space_ost_MPR_AX,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
123,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6646073,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-092,HA-01-092-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
124,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6803502,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-069,HA-01-069-7301,SCA8,AX_T1,...,0.0,-2.0,-1.0,-6.0,-3.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
125,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7543232,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-077,HA-01-077-7301,CANVAS,AX_MPRAGE_T1_PO_0mm__2_0mm,...,-1.0,0.0,-2.0,-17.0,-11.0,-28.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
126,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7610044,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-084,HA-01-084-7301,SCA27B,Sag_T1_3D_MPRAGE_Wave,...,0.0,-2.0,0.0,-2.0,-3.0,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
130,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7622589,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-057,HA-01-057-7301,SCA3,10_Ax_T1,...,0.0,0.0,0.0,-2.0,0.0,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
134,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7665334,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
137,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7749218,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-110,HA-01-110-7301,SCA27B,C__SAG_MPR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
140,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7871300,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-066,HA-01-066-7301,SCA1,VI_Axial_T1_FSE_11,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
144,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7890257,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-072,HA-01-072-7301,SCA1,100___MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
145,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7997058,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-059,HA-01-059-7301,SCA6,COR_T1_POST_MPR,...,0.0,0.0,-1.0,-2.0,-6.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
150,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8231339,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-111,HA-01-111-7301,SCA27B,2__Sag_T1_3D_Mprage_Promo,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
152,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8254224,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-068,HA-01-068-7301,SCA3,Ax_T1_3D_Bravo,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
158,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8344492,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-075,HA-01-075-7301,SCA2,Post_Sag_T1_3D_MPRAGE_DL,...,0.0,-1.0,-3.0,-8.0,-6.0,-14.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
161,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8786142,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
165,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1847722,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-022,HA-01-022-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
166,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2823737,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-018,HA-01-018-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
167,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3699762,8__Ax_3D_BRAVO,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-097,HA-01-097-7301,SCA27B,8__Ax_3D_BRAVO,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
170,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4029230,AAHead_Scout,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-061,HA-01-061-7301,SCA2,T1_Sag,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...

**Drop Row Based on Value of Column**

Define the column, condition, and value for dropping rows
- column = 'your_column_name'
- condition = 'above'  # Options: 'equal', 'above', 'below'

In [15]:
data_df.columns

Index(['paths', 'Nifti_File_Path', 'subid', 'session', 'selected',
       'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type',
       ...
       'TotalSection3Score', 'TotalSection4Score', 'TotalSection5Score',
       'CNRSTotColAScore', 'CNRSTotColBScore', 'CNRSTotScore', 'roi_path',
       'conn_path', 'dataset', 'oatgs'],
      dtype='object', length=118)

Set the parameters for dropping rows

In [16]:
column = 'selected'  # The column you'd like to evaluate
condition = 'not'  # The condition to check ('equal', 'above', 'below', 'not')
value = 1 # The value to drop if found

In [17]:
data_df, other_df = cal_palm.drop_rows_based_on_value(column, condition, value)
display(data_df)

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection3Score,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
7,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6930044,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
8,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1355923,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-103,HA-01-103-7301,SCA27B,T1_MPRAGE_SAG,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
13,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1539729,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
15,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16067027,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
24,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16721995,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
26,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,20508602,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
33,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2071224,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-099,HA-01-099-7301,SCA27B,15_Sag_T1_3D_MP_PR_Cor_MPR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
36,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2368336,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-002,HA-01-002-7301,SCA6,C__Cor_T1_3D,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
38,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2369031,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-091,HA-01-091-7301,SCA27B,MPR_Coronal_Ref___Revised_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
43,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,315616,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
45,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3241194,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-089,HA-01-089-7301,SCA27B,27_Sag_T1_3D_MP_mitigation,...,-4.0,0.0,-2.0,-7.0,-10.0,-17.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
52,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,43218874,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
54,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4392765,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-105,HA-01-105-7301,SCA27B,Sag_T1_3D_MPRAG_MPR_Ax_MPR,...,0.0,0.0,-3.0,-7.0,-1.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
61,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4401431,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-051,HA-01-051-7301,SCA6,Sag_T1_3D_MPRAG_mitigation,...,-1.0,-4.0,-4.0,-18.0,-16.0,-34.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
63,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4530107,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-010,HA-01-010-7301,SCA2,COR_MPR_PRE,...,0.0,-1.0,-1.0,-3.0,-9.0,-12.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
67,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4552969,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-019,HA-01-019-7301,SCA1,_MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
74,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4722004,C__Ax_3D_VIBE,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-006,HA-01-006-7301,SCA3,C__Cor_T1_FS,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
79,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4783569,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-015,HA-01-015-7301,SCA3,Post_t1_SAG_MPRAGE,...,-2.0,-6.0,-5.0,-11.0,-16.0,-27.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
84,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4792757,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-031,HA-01-031-7301,SCA1,AXIAL_MPRAGE_RECONS,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
85,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5180657,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-032,HA-01-032-7301,SCA6,501__T2_Sag_3D_Brain_VIEW,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
87,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5199392,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-076,HA-01-076-7301,SCA3,PRE_Cor_T1_3D_Bravo_MPR,...,-1.0,-4.0,-2.0,-12.0,-10.0,-22.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
89,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5390756,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-047,HA-01-047-7301,SCA6/8,6__Sag_T1,...,0.0,0.0,0.0,-3.0,-1.0,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
92,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5410367,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-034,HA-01-034-7301,SCA1,COR_MPRAGE_REFORM,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
94,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5709549,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-039,HA-01-039-7301,SCA3,3d_Sag_T1,...,-3.0,-3.0,-3.0,-10.0,-9.0,-19.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
95,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5737974,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-046,HA-01-046-7301,SCA3,T1_TSE_AXIAL_3MM,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
97,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5766687,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-087,HA-01-087-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
101,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5997510,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-093,HA-01-093-7301,SCA27B,MPR_Ob_Cor_A____1_0_th_1_0,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
110,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6038408,9,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-098,HA-01-098-7301,SCA27B,COR_T1_MPR,...,0.0,-4.0,-2.0,-9.0,-7.0,-16.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
111,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6227801,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-055,HA-01-055-7301,SCA2,PRE_SAG_3D_T1_MPR,...,-3.0,-1.0,-7.0,-9.0,-14.0,-23.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
116,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6241170,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-085,HA-01-085-7301,SCA27B,12_Post_3D_Ax_T1_BRAVO,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
117,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6350474,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-108,HA-01-108-7301,CANVAS,SAG_T1_FS_Space_ost_MPR_AX,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
123,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6646073,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-092,HA-01-092-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
124,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6803502,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-069,HA-01-069-7301,SCA8,AX_T1,...,0.0,-2.0,-1.0,-6.0,-3.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
125,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7543232,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-077,HA-01-077-7301,CANVAS,AX_MPRAGE_T1_PO_0mm__2_0mm,...,-1.0,0.0,-2.0,-17.0,-11.0,-28.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
126,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7610044,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-084,HA-01-084-7301,SCA27B,Sag_T1_3D_MPRAGE_Wave,...,0.0,-2.0,0.0,-2.0,-3.0,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
130,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7622589,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-057,HA-01-057-7301,SCA3,10_Ax_T1,...,0.0,0.0,0.0,-2.0,0.0,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
134,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7665334,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
137,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7749218,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-110,HA-01-110-7301,SCA27B,C__SAG_MPR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
140,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7871300,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-066,HA-01-066-7301,SCA1,VI_Axial_T1_FSE_11,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
144,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7890257,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-072,HA-01-072-7301,SCA1,100___MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
145,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7997058,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-059,HA-01-059-7301,SCA6,COR_T1_POST_MPR,...,0.0,0.0,-1.0,-2.0,-6.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
150,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8231339,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-111,HA-01-111-7301,SCA27B,2__Sag_T1_3D_Mprage_Promo,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
152,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8254224,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-068,HA-01-068-7301,SCA3,Ax_T1_3D_Bravo,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
158,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8344492,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-075,HA-01-075-7301,SCA2,Post_Sag_T1_3D_MPRAGE_DL,...,0.0,-1.0,-3.0,-8.0,-6.0,-14.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
161,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8786142,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
165,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1847722,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-022,HA-01-022-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
166,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2823737,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-018,HA-01-018-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
167,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3699762,8__Ax_3D_BRAVO,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-097,HA-01-097-7301,SCA27B,8__Ax_3D_BRAVO,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
170,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4029230,AAHead_Scout,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-061,HA-01-061-7301,SCA2,T1_Sag,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...

Standardize

In [18]:
# Remove anything you don't want to standardize
cols_not_to_standardize = ['subid']

In [19]:
# data_df = cal_palm.standardize_columns(cols_not_to_standardize)
data_df

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection3Score,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
7,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6930044,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
8,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1355923,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-103,HA-01-103-7301,SCA27B,T1_MPRAGE_SAG,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
13,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1539729,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
15,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16067027,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
24,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16721995,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
26,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,20508602,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
33,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2071224,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-099,HA-01-099-7301,SCA27B,15_Sag_T1_3D_MP_PR_Cor_MPR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
36,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2368336,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-002,HA-01-002-7301,SCA6,C__Cor_T1_3D,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
38,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2369031,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-091,HA-01-091-7301,SCA27B,MPR_Coronal_Ref___Revised_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
43,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,315616,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
45,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3241194,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-089,HA-01-089-7301,SCA27B,27_Sag_T1_3D_MP_mitigation,...,-4.0,0.0,-2.0,-7.0,-10.0,-17.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
52,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,43218874,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
54,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4392765,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-105,HA-01-105-7301,SCA27B,Sag_T1_3D_MPRAG_MPR_Ax_MPR,...,0.0,0.0,-3.0,-7.0,-1.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
61,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4401431,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-051,HA-01-051-7301,SCA6,Sag_T1_3D_MPRAG_mitigation,...,-1.0,-4.0,-4.0,-18.0,-16.0,-34.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
63,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4530107,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-010,HA-01-010-7301,SCA2,COR_MPR_PRE,...,0.0,-1.0,-1.0,-3.0,-9.0,-12.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
67,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4552969,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-019,HA-01-019-7301,SCA1,_MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
74,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4722004,C__Ax_3D_VIBE,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-006,HA-01-006-7301,SCA3,C__Cor_T1_FS,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
79,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4783569,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-015,HA-01-015-7301,SCA3,Post_t1_SAG_MPRAGE,...,-2.0,-6.0,-5.0,-11.0,-16.0,-27.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
84,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4792757,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-031,HA-01-031-7301,SCA1,AXIAL_MPRAGE_RECONS,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
85,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5180657,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-032,HA-01-032-7301,SCA6,501__T2_Sag_3D_Brain_VIEW,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
87,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5199392,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-076,HA-01-076-7301,SCA3,PRE_Cor_T1_3D_Bravo_MPR,...,-1.0,-4.0,-2.0,-12.0,-10.0,-22.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
89,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5390756,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-047,HA-01-047-7301,SCA6/8,6__Sag_T1,...,0.0,0.0,0.0,-3.0,-1.0,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
92,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5410367,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-034,HA-01-034-7301,SCA1,COR_MPRAGE_REFORM,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
94,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5709549,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-039,HA-01-039-7301,SCA3,3d_Sag_T1,...,-3.0,-3.0,-3.0,-10.0,-9.0,-19.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
95,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5737974,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-046,HA-01-046-7301,SCA3,T1_TSE_AXIAL_3MM,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
97,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5766687,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-087,HA-01-087-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
101,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5997510,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-093,HA-01-093-7301,SCA27B,MPR_Ob_Cor_A____1_0_th_1_0,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
110,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6038408,9,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-098,HA-01-098-7301,SCA27B,COR_T1_MPR,...,0.0,-4.0,-2.0,-9.0,-7.0,-16.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
111,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6227801,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-055,HA-01-055-7301,SCA2,PRE_SAG_3D_T1_MPR,...,-3.0,-1.0,-7.0,-9.0,-14.0,-23.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
116,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6241170,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-085,HA-01-085-7301,SCA27B,12_Post_3D_Ax_T1_BRAVO,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
117,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6350474,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-108,HA-01-108-7301,CANVAS,SAG_T1_FS_Space_ost_MPR_AX,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
123,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6646073,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-092,HA-01-092-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
124,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6803502,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-069,HA-01-069-7301,SCA8,AX_T1,...,0.0,-2.0,-1.0,-6.0,-3.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
125,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7543232,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-077,HA-01-077-7301,CANVAS,AX_MPRAGE_T1_PO_0mm__2_0mm,...,-1.0,0.0,-2.0,-17.0,-11.0,-28.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
126,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7610044,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-084,HA-01-084-7301,SCA27B,Sag_T1_3D_MPRAGE_Wave,...,0.0,-2.0,0.0,-2.0,-3.0,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
130,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7622589,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-057,HA-01-057-7301,SCA3,10_Ax_T1,...,0.0,0.0,0.0,-2.0,0.0,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
134,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7665334,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
137,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7749218,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-110,HA-01-110-7301,SCA27B,C__SAG_MPR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
140,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7871300,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-066,HA-01-066-7301,SCA1,VI_Axial_T1_FSE_11,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
144,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7890257,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-072,HA-01-072-7301,SCA1,100___MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
145,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7997058,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-059,HA-01-059-7301,SCA6,COR_T1_POST_MPR,...,0.0,0.0,-1.0,-2.0,-6.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
150,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8231339,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-111,HA-01-111-7301,SCA27B,2__Sag_T1_3D_Mprage_Promo,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
152,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8254224,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-068,HA-01-068-7301,SCA3,Ax_T1_3D_Bravo,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
158,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8344492,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-075,HA-01-075-7301,SCA2,Post_Sag_T1_3D_MPRAGE_DL,...,0.0,-1.0,-3.0,-8.0,-6.0,-14.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
161,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8786142,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
165,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1847722,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-022,HA-01-022-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
166,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2823737,Cor_3D_SPGR,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-018,HA-01-018-7301,SCA3,Cor_3D_SPGR,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
167,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3699762,8__Ax_3D_BRAVO,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-097,HA-01-097-7301,SCA27B,8__Ax_3D_BRAVO,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...
170,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4029230,AAHead_Scout,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-061,HA-01-061-7301,SCA2,T1_Sag,...,0.0,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...

Convert Categorical to Ordinal

One Hot Encode

In [20]:
# import pandas as pd
# one_hot = pd.get_dummies(data_df['cluster_label'], prefix='cluster_label', dtype=int)
# data_df = data_df.join(one_hot)
# data_df

# 02 - Define Your Formula

This is the formula relating outcome to predictors, and takes the form:
- y = B0 + B1 + B2 + B3 + . . . BN

It is defined using the columns of your dataframe instead of the variables above:
- 'Apples_Picked ~ hours_worked + owns_apple_picking_machine'

____
**ANOVA**
- Tests differences in means for one categorical variable.
- formula = 'Outcome ~ C(Group1)'

**2-Way ANOVA**
- Tests differences in means for two categorical variables without interaction.
- formula = 'Outcome ~ C(Group1) + C(Group2)'

**2-Way ANOVA with Interaction**
- Tests for interaction effects between two categorical variables.
- formula = 'Outcome ~ C(Group1) * C(Group2)'

**ANCOVA**
- Similar to ANOVA, but includes a covariate to control for its effect.
- formula = 'Outcome ~ C(Group1) + Covariate'

**2-Way ANCOVA**
- Extends ANCOVA with two categorical variables and their interaction, controlling for a covariate.
- formula = 'Outcome ~ C(Group1) * C(Group2) + Covariate'

**Multiple Regression**
- Assesses the impact of multiple predictors on an outcome.
- formula = 'Outcome ~ Predictor1 + Predictor2'

**Simple Linear Regression**
- Assesses the impact of a single predictor on an outcome.
- formula = 'Outcome ~ Predictor'

**MANOVA**
- Assesses multiple dependent variables across groups.
- Note: Not typically set up with a formula in statsmodels. Requires specialized functions.

____
Use the printout below to design your formula. 
- Left of the "~" symbol is the thing to be predicted. 
- Right of the "~" symbol are the predictors. 
- ":" indicates an interaction between two things. 
- "*" indicates and interactions AND it accounts for the simple effects too. 
- "+" indicates that you want to add another predictor.

In [22]:
data_df.columns

Index(['paths', 'Nifti_File_Path', 'subid', 'session', 'selected',
       'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type',
       ...
       'TotalSection3Score', 'TotalSection4Score', 'TotalSection5Score',
       'CNRSTotColAScore', 'CNRSTotColBScore', 'CNRSTotScore', 'roi_path',
       'conn_path', 'dataset', 'oatgs'],
      dtype='object', length=118)

In [23]:
formula = f"Nifti_File_Path ~ {variable}"

# 02 - Visualize Your Design Matrix

This is the explanatory variable half of your regression formula
_______________________________________________________
Create Design Matrix: Use the create_design_matrix method. You can provide a list of formula variables which correspond to column names in your dataframe.

- voxelwise_variable_list = A list containing the names of each variable that has voxelwise variables. Plainly, the variables that represent niftis. 
- By default, an intercept will be added unless you set intercept=False
- **don't explicitly add the 'intercept' column. I'll do it for you.**

In [24]:
voxelwise_variable_list=['Nifti_File_Path']

If you want to run voxelwise INTERACTIONS, then you should specify the exact terms, exactly as specified in your above formula, here. 
- For example, if Formula is outcome ~ voxelwise_var1 * age + dog_number, then voxelwise_interaction_terms are ['voxelwise_var1 * age]
- Set voxelwise_interaction_terms = [] (left as an empty list) if you have no interactions with voxelwise variables

In [25]:
voxelwise_interaction_terms = []

Make sure ANY voxelwise variables are in formula.

In [26]:
outcome_df, design_matrix = cal_palm.define_design_matrix(formula, data_df, add_intercept=False,
                                                          voxelwise_variable_list=voxelwise_variable_list, 
                                                          voxelwise_interaction_terms=voxelwise_interaction_terms)
design_matrix

     Gait
4     0.0
7     0.0
8    -1.0
13    0.0
15    0.0
24    0.0
26    0.0
33   -1.5
36   -6.0
38   -1.0
43    0.0
45   -1.0
52    0.0
54   -2.5
61   -8.0
63   -1.0
67    0.0
74   -3.0
79   -2.0
84   -1.0
85    0.0
87   -8.0
89   -8.0
92    0.0
94   -3.0
95   -1.0
97    0.0
101  -0.5
110  -6.0
111  -2.5
116  -1.0
117  -1.0
123  -1.5
124   0.0
125  -1.5
126  -1.0
130  -1.0
134   0.0
137  -2.5
140  -1.0
144  -2.0
145  -1.5
150   0.0
152   0.0
158  -0.5
161   0.0
165  -1.0
166   0.0
167  -1.0
170  -2.5
171  -1.0
172  -4.0
175  -8.0
176   0.0
178  -6.5
179  -5.0

In [27]:
design_matrix.shape

(56, 1)

# 03 - Visualize Your Dependent Variable

I have generated this for you based on the formula you provided

In [28]:
outcome_df

                                       Nifti_File_Path
4    /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
7    /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
8    /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
13   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
15   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
24   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
26   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
33   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
36   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
38   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
43   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
45   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
52   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
54   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
61   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
63   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
67   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
74   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
79   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
84   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
85   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
87   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
89   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
92   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
94   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
95   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
97   /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
101  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
110  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
111  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
116  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
117  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
123  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
124  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
125  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
126  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
130  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
134  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
137  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
140  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
144  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
145  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
150  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
152  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
158  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
161  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
165  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
166  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
167  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
170  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
171  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
172  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
175  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
176  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
178  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
179  /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...

# 04 - Generate Contrasts

Generate a Contrast Matrix
- This is different from the contrast matrices used in cell-means regressions such as in PALM, but it is much more powerful. 



For more information on contrast matrices, please refer to this: https://cran.r-project.org/web/packages/codingMatrices/vignettes/codingMatrices.pdf

Generally, these drastically effect the results of ANOVA. However, they are mereley a nuisance for a regression.
In essence, they assess if coefficients are significantly different

________________________________________________________________
A coding matrix (a contrast matrix if it sums to zero) is simply a way of defining what coefficients to evaluate and how to evaluate them. 
If a coefficient is set to 1 and everything else is set to zero, we are taking the mean of the coefficient's means and assessing if they significantly
deviate from zero--IE we are checking if it had a significant impact on the ability to predict the depdendent variable.
If a coefficient is set to 1, another is -1, and others are 0, we are assessing how the means of the two coefficients deviate from eachother. 
If several coefficients are 1 and several others are -1, we are assessing how the group-level means of the two coefficients deviate from eachother.
If a group of coefficients are 1, a group is -1, and a group is 0, we are only assessing how the groups +1 and -1 have differing means. 

1: This value indicates that the corresponding variable's coefficient in the model is included in the contrast. It means you are interested in estimating the effect of that variable.

0: This value indicates that the corresponding variable's coefficient in the model is not included in the contrast. It means you are not interested in estimating the effect of that variable.

-1: This value indicates that the corresponding variable's coefficient in the model is included in the contrast, but with an opposite sign. It means you are interested in estimating the negative effect of that variable.

----------------------------------------------------------------
The contrast matrix is typically a matrix with dimensions (number of contrasts) x (number of regression coefficients). Each row of the contrast matrix represents a contrast or comparison you want to test.

For example, let's say you have the following regression coefficients in your model:

Intercept, Age, connectivity, Age_interaction_connectivity
A contrast matric has dimensions of [n_predictors, n_experiments] where each experiment is a contrast

If you want to test the hypothesis that the effect of Age is significant, you can set up a contrast matrix with a row that specifies this contrast (actually an averaging vector):
```
[0,1,0,0]. This is an averaging vector because it sums to 1
```
This contrast will test the coefficient corresponding to the Age variable against zero.


If you want to test the hypothesis that the effect of Age is different from the effect of connectivity, you can set up a contrast matrix with two rows:
```
[0,1,−1,0]. This is a contrast because it sums to 0
```

Thus, if you want to see if any given effect is significant compared to the intercept (average), you can use the following contrast matrix:
```
[1,0,0,0]
[-1,1,0,0]
[-1,0,1,0]
[-1,0,0,1] actually a coding matrix of averaging vectors
```

The first row tests the coefficient for Age against zero, and the second row tests the coefficient for connectivity against zero. The difference between the two coefficients can then be assessed.
_____
You can define any number of contrasts in the contrast matrix to test different hypotheses or comparisons of interest in your regression analysis.

It's important to note that the specific contrasts you choose depend on your research questions and hypotheses. You should carefully consider the comparisons you want to make and design the contrast matrix accordingly.

- Examples:
    - [Two Sample T-Test](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/GLM#Two-Group_Difference_.28Two-Sample_Unpaired_T-Test.29)
    - [One Sample with Covariate](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/GLM#Single-Group_Average_with_Additional_Covariate)

In [29]:
contrast_matrix = cal_palm.generate_basic_contrast_matrix(design_matrix)

Here is a basic contrast matrix set up to evaluate the significance of each variable.
Here is an example of what your contrast matrix looks like as a dataframe:
   Gait
0     1
Below is the same contrast matrix, but as an array.
Copy it into a cell below and edit it for more control over your analysis.
[
    [1],
]

In [30]:
contrast_matrix = [
    [1]
]

In [31]:
contrast_matrix_df = cal_palm.finalize_contrast_matrix(design_matrix=design_matrix, 
                                                    contrast_matrix=contrast_matrix) 
contrast_matrix_df

   Gait
0     1

# 05 - Generate Files
Standardization during regression is critical. 
- data_transform_method='standardize' will ensure the voxelwise values are standardized
    - if you design matrix has a column called 'Dataset', the standardization will standardize values within each dataset individually, which is as should be done normally.
    - If you call data_transform_method='standardize' without having a 'Dataset' column in your design matrix, the entire collection of images will be standardized. This is potentially dangerous and misleading. Be careful, and consider not standardizing at all, or going back and adding a 'Dataset' column. 

Mask Path
- set mask_path to the path of your local brain mask which matches the resolution of the files you have collected. Typically this is an MNI 152 brain mask. 
    - download one here: https://nilearn.github.io/dev/modules/generated/nilearn.datasets.load_mni152_brain_mask.html

In [32]:
mask_path = '/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/resources/MNI152_T1_2mm_brain_mask.nii'

Define exchangeability block
- Set to none if you don't know
- If you are running multiple cohorts, set exchangeability block to be the column which has each group in it, with groups being indicated by integers.

In [33]:
exchangeability_col = None

In [34]:
from calvin_utils.permutation_analysis_utils.voxelwise_regression_prep import RegressionPrep
preparer = RegressionPrep(design_matrix=design_matrix, 
                          contrast_matrix=contrast_matrix_df, 
                          outcome_df=outcome_df, 
                          out_dir=out_dir,
                          voxelwise_variables=voxelwise_variable_list, 
                          voxelwise_interactions=voxelwise_interaction_terms,
                          mask_path=mask_path, 
                          exchangeability_block=None, 
                          data_transform_method='standardize',
                          weights=None)
dataset_dict, json_path = preparer.run()

Attempting to import from pandas series. expecting PD series full of filenames. Will fail unless a series is provided using df["path_column"]
design_tensor shape: (56, 1, 1)
outcome_data shape: (56, 1, 228483)

# 06 - Run the Voxelwise Regression

In [35]:
from calvin_utils.permutation_analysis_utils.voxelwise_regression import VoxelwiseRegression
regression = VoxelwiseRegression(json_path, mask_path=mask_path, out_dir=out_dir, regression_type='linear', n_permutations=1000)
results = regression.run_all_outputs()

Outcome is not all binary. You should ensure regression_type='linear'. Detected regression_type: linear

Running regression for output 0

running permutations: 100%|██████████| 1000/1000 [02:44<00:00,  6.08it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00,  2.33it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00, 33.51it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00, 35.84it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00, 87.00it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00, 34.01it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00, 77.05it/s]
Saving files: 100%|██████████| 1/1 [00:00<00:00, 64.77it/s]

View results

In [36]:
html = regression.visualize_results(open_browser=True)

Test the voxelwise model
- Run a LOOCV, generating prediction maps
- Best to use this when dependent variable is the clinical outcome, not a voxelwise map.

In [ ]:
cv = regression.run_cross_validation(y_true=data_df[variable], subject_files=data_df["Nifti_File_Path"])

# 07 - Predict another dataset using the Fitted Voxelwise Regression

Import Data

In [ ]:
# Specify the path to your CSV file containing NIFTI paths
input_csv_path = '/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/metadata/cleaned_information/master.csv'
sheet = None

In [ ]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
cal_palm = CalvinStatsmodelsPalm(input_csv_path=input_csv_path, output_dir=out_dir, sheet=sheet)
test_df = cal_palm.read_and_display_data()
test_df

**Handle NANs**
- Set drop_nans=True is you would like to remove NaNs from data
- Provide a column name or a list of column names to remove NaNs from

In [ ]:
test_df.columns

In [ ]:
drop_list = ['DX_BASELINE', 'fluid_atrophy_path_smoothed']

In [ ]:
test_df = cal_palm.drop_nans_from_columns(columns_to_drop_from=drop_list)
test_df

**Drop Row Based on Value of Column**

Define the column, condition, and value for dropping rows
- column = 'your_column_name'
- condition = 'above'  # Options: 'equal', 'above', 'below'

In [ ]:
test_df.columns

Set the parameters for dropping rows

In [ ]:
column = 'Cohort'  # The column you'd like to evaluate
condition = 'not'  # The condition to check ('equal', 'above', 'below', 'not')
value = 'Validation' # The value to drop if found

In [ ]:
test_df, _ = cal_palm.drop_rows_based_on_value(column, condition, value)
display(test_df)

Convert Categorical to Ordinal

Misc Changes

In [ ]:
import pandas as pd
one_hot = pd.get_dummies(test_df['DX_BASELINE'], prefix='DX_BASELINE', dtype=int)
test_df = test_df.join(one_hot)
test_df

Prepare Design and Outcome Matrices

In [ ]:
test_outcome_df, test_design_matrix = cal_palm.define_design_matrix(formula, test_df, add_intercept=False,
                                                          voxelwise_variable_list=voxelwise_variable_list, 
                                                          voxelwise_interaction_terms=voxelwise_interaction_terms)
test_design_matrix

Predict Another Dataset
- Import another dataset (currently cannot normalized to the other data's distribution, so make sure they are on the same scale)

In [ ]:
from calvin_utils.permutation_analysis_utils.voxelwise_regression_prep import RegressionPrep
preparer = RegressionPrep(design_matrix=test_design_matrix, 
                          contrast_matrix=contrast_matrix_df, 
                          outcome_df=test_outcome_df, 
                          out_dir=out_dir+'/test_predictions',
                          voxelwise_variables=voxelwise_variable_list, 
                          voxelwise_interactions=voxelwise_interaction_terms,
                          mask_path=mask_path, 
                          exchangeability_block=None, 
                          data_transform_method=None,
                          weights=None,
                          formula=formula)
test_dataset_dict, test_json_path = preparer.run()

- Run the fitted voxelwise model to generate prediction maps

In [ ]:
from calvin_utils.permutation_analysis_utils.voxelwise_regression import VoxelwiseRegression
regression = VoxelwiseRegression(test_json_path, mask_path=mask_path, out_dir=out_dir+'/test_predictions/regression_0', regression_type='linear', n_permutations=0)
results = regression.run_prediction(params_dir='/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/csf/regression_0')

Measure patient damage score with above Maps (from the above model's outputs or patient-wise predictions it has made) to measure

In [ ]:
test_df.columns

In [ ]:
patient_nifti_col = ""  # e.g., "composite_atrophy_path_smoothed"
metric = ""             # fill with DamageScorer metric (e.g., "avg_in_subject")
threshold = ThresholdSpec(mode="above", value=2.0)  # set to None to skip thresholding
output_col = ""         # e.g., "pred0_avg_in_subject"
prediction_dir = ""     # e.g., f"{out_dir}/test_predictions/regression_0"
reference_nifti_path = ""  # set this OR prediction_dir (not both)

In [ ]:
from calvin_utils.permutation_analysis_utils import PredictionDamageScorer, ThresholdSpec
scorer = PredictionDamageScorer(df=df, mask_path=mask_path)

df = scorer.add_score_column(
    patient_nifti_col=patient_nifti_col,
    metric=metric,
    threshold=threshold,
    column_name=output_col,
    prediction_dir=prediction_dir,                              # Either set this
    reference_nifti_path=reference_nifti_path,                  # or this, but not both.
)

Use damage scores to perform regression or classification

In [ ]:
from calvin_utils.permutation_analysis_utils import BrainModelEvaluation

# ---- user-fill parameters ----
df = df  # dataframe containing prediction/observation columns
task = "regression"  # "regression" or "classification"

# Regression options
fitted_model = results  # statsmodels fitted model (set to None to use columns instead)
prediction_cols = ["pred_score"]  # used only if fitted_model is None
observation_cols = ["outcome"]    # used only if fitted_model is None
exog_df = design_matrix_df        # required if fitted_model is None

# Common options
out_dir = None  # set to a folder to save plots
show = True     # set False to suppress plotting

# ---- run ----
evaluator = BrainModelEvaluation(
    df=df,
    task=task,
    fitted_model=fitted_model,
    prediction_cols=prediction_cols,
    observation_cols=observation_cols,
    exog_df=exog_df,
    out_dir=out_dir,
    show=show,
)
evaluator.run()

That's all

-Calvin