Path to directory to save to

In [1]:
# Specify where you want to save your results to
out_dir = '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions_clusters'

Import Niftis
- These are EXPECTED to have subject IDs which are IDENTICAL to the subject IDs that go in the covarite DF column names below
- Column labels are subject IDs. 
- This is expected to ultimately have the form:

|        |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 |  10 | ... |  40 |  41 |  42 |  43 |  45 |  46 |  47 |  48 |  49 |  50 |
|----------|------------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|-----------|------------|-----|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
| Voxel 1     | 3          | 4         | 7         | 2         | 2         | 2         | 9         | 4         | 7         | 5          | ... | 5           | 2           | 7           | 7           | 3           | 8           | 8           | 1           | 1           | 3           |
| . . .      | ...         | ...        | ...         | ...         | ...         | ...         | ...         | ...         | ...         | ...          | ... | ...           | ...           | ...           | ...           | ...           | ...           | 7           | ...           | ...           | ...           |
| Voxel N     | 2          | 1         | 0         | 1         | 3         | 4         | 9         | 5         | 8         | 6          | ... | 6           | 3           | 8           | 8           | 4           | 9           | 9           | 2           | 2           | 4           |

In [2]:
import_path = '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/*/regression'
file_target= 'contrast_tval_0.nii.gz'

In [3]:
from calvin_utils.file_utils.import_functions import GiiNiiFileImport
giinii = GiiNiiFileImport(import_path=import_path, file_column=None, file_pattern=file_target, mask_path='/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/resources/MNI152_T1_2mm_brain_mask.nii')
nimg_df = giinii.run()
nimg_df

Attempting to import from globbable path. Expecting globbable filenames.
Attempting to import from: /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/*/regression/contrast_tval_0.nii.gz

,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec1BCauseDistress-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/VisualTotal-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4AConcerns-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec1BWorries-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec3ASensoryExp-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec3ARepetitiveMovements-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4BTroubleUnderstand-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/CategorySwitchFailS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/LimbAtaxia-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/DigitSpanBackwardRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol4A-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4BDistant-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol5A-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec3BOverwhelmed-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol3B-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/CubeDrawRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol1B-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/FingerToNoseTestLeft-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4BIndifferent-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec5BUnaware-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz
0,-0.202598,-1.693670,1.327816,-0.631943,0.675608,1.031692,1.715078,-1.098741,0.347911,-0.500006,...,1.518419,1.617669,0.706636,0.040053,0.111208,-1.693670,-0.191376,-0.266099,0.920682,0.939401
1,0.333841,-0.820158,1.442371,-0.191223,0.880578,1.016053,1.596251,-0.549600,0.095668,-0.580238,...,1.990575,1.446794,0.963461,1.091855,1.189612,-0.820158,0.411615,-0.431684,0.849941,0.744624
2,0.653452,-0.173627,1.241306,-0.134312,1.141192,0.704933,1.363818,-0.182198,0.466255,-0.447516,...,2.085260,1.269684,0.738414,1.640546,1.699404,-0.173627,0.620026,0.197538,0.850160,0.691522
3,-0.748365,-1.933073,0.972827,-1.229844,0.536972,1.109099,1.598829,-1.298200,0.374616,-0.362298,...,0.826263,1.624637,0.106559,-0.835941,-0.759052,-1.933073,-0.878920,-0.175256,0.386680,-0.118744
4,0.013920,-1.111829,1.050865,-0.612414,0.772146,1.072558,1.495157,-0.735713,0.219973,-0.399386,...,1.299332,1.397666,0.345099,0.159789,0.240728,-1.111829,-0.058822,-0.183760,0.489541,0.092445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228478,0.698546,0.087306,0.888311,0.179315,0.332748,1.588359,1.616349,-0.595107,-1.029524,1.571551,...,1.032211,1.998715,0.640755,-0.792350,-0.668628,0.087306,0.772142,-1.134741,1.114900,0.665958
228479,0.208731,-0.769224,0.547282,0.638051,0.003754,1.295069,1.086323,0.059486,-1.124230,1.344252,...,0.840349,1.528531,0.573313,-1.689378,-1.574268,-0.769224,0.634017,-0.843344,0.716521,0.106645
228480,-0.053717,-1.038921,0.744095,0.275189,0.115882,1.503815,1.448022,-0.109066,-1.067959,1.259372,...,0.833278,1.788223,0.577942,-1.966523,-1.773735,-1.038921,0.350617,-0.931952,1.303979,0.085468
228481,-0.004865,-0.928774,0.776570,0.183064,0.092558,1.469954,1.315908,-0.125515,-1.226014,1.312109,...,0.672627,1.644598,0.501021,-1.736110,-1.533321,-0.928774,0.248774,-1.169341,1.185628,0.098265
228482,0.388667,-0.827141,0.962475,0.477893,0.425092,1.392319,1.181544,0.043617,-1.427849,1.343364,...,0.933800,1.460796,0.672162,-1.370332,-1.154615,-0.827141,0.661234,-1.135073,0.850045,-0.118865

Name columns corresponding to niftis to multiply by -1

In [4]:
cols_to_flip = [
    "Raw",
    "ExecutiveTotal-on-Nifti_File_Path", "LanguageTotal-on-Nifti_File_Path", "MemoryTotal-on-Nifti_File_Path", "VisualTotal-on-Nifti_File_Path", "VerbalRegSum-on-Nifti_File_Path"
]

In [5]:
cols_to_drop = ["TotalCCASFailScore-on-Nifti_File_Path", "CNRSTotScore-on-Nifti_File_Path", "TotalBarsScore-on-Nifti_File_Path"]
for col in nimg_df.columns:
    if any(drop_col in col for drop_col in cols_to_drop):
        nimg_df.pop(col)
display(nimg_df)

,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec1BCauseDistress-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/VisualTotal-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4AConcerns-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec1BWorries-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec3ASensoryExp-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec3ARepetitiveMovements-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4BTroubleUnderstand-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/CategorySwitchFailS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/LimbAtaxia-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/DigitSpanBackwardRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol4A-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4BDistant-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol5A-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec3BOverwhelmed-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol3B-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/CubeDrawRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ScoreCol1B-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/FingerToNoseTestLeft-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec4BIndifferent-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/Sec5BUnaware-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz
0,-0.202598,-1.693670,1.327816,-0.631943,0.675608,1.031692,1.715078,-1.098741,0.347911,-0.500006,...,1.518419,1.617669,0.706636,0.040053,0.111208,-1.693670,-0.191376,-0.266099,0.920682,0.939401
1,0.333841,-0.820158,1.442371,-0.191223,0.880578,1.016053,1.596251,-0.549600,0.095668,-0.580238,...,1.990575,1.446794,0.963461,1.091855,1.189612,-0.820158,0.411615,-0.431684,0.849941,0.744624
2,0.653452,-0.173627,1.241306,-0.134312,1.141192,0.704933,1.363818,-0.182198,0.466255,-0.447516,...,2.085260,1.269684,0.738414,1.640546,1.699404,-0.173627,0.620026,0.197538,0.850160,0.691522
3,-0.748365,-1.933073,0.972827,-1.229844,0.536972,1.109099,1.598829,-1.298200,0.374616,-0.362298,...,0.826263,1.624637,0.106559,-0.835941,-0.759052,-1.933073,-0.878920,-0.175256,0.386680,-0.118744
4,0.013920,-1.111829,1.050865,-0.612414,0.772146,1.072558,1.495157,-0.735713,0.219973,-0.399386,...,1.299332,1.397666,0.345099,0.159789,0.240728,-1.111829,-0.058822,-0.183760,0.489541,0.092445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228478,0.698546,0.087306,0.888311,0.179315,0.332748,1.588359,1.616349,-0.595107,-1.029524,1.571551,...,1.032211,1.998715,0.640755,-0.792350,-0.668628,0.087306,0.772142,-1.134741,1.114900,0.665958
228479,0.208731,-0.769224,0.547282,0.638051,0.003754,1.295069,1.086323,0.059486,-1.124230,1.344252,...,0.840349,1.528531,0.573313,-1.689378,-1.574268,-0.769224,0.634017,-0.843344,0.716521,0.106645
228480,-0.053717,-1.038921,0.744095,0.275189,0.115882,1.503815,1.448022,-0.109066,-1.067959,1.259372,...,0.833278,1.788223,0.577942,-1.966523,-1.773735,-1.038921,0.350617,-0.931952,1.303979,0.085468
228481,-0.004865,-0.928774,0.776570,0.183064,0.092558,1.469954,1.315908,-0.125515,-1.226014,1.312109,...,0.672627,1.644598,0.501021,-1.736110,-1.533321,-0.928774,0.248774,-1.169341,1.185628,0.098265
228482,0.388667,-0.827141,0.962475,0.477893,0.425092,1.392319,1.181544,0.043617,-1.427849,1.343364,...,0.933800,1.460796,0.672162,-1.370332,-1.154615,-0.827141,0.661234,-1.135073,0.850045,-0.118865

Run Umap

In [29]:
from calvin_utils.ml_utils.brain_umap import BrainUmap
umapper = BrainUmap(data=nimg_df, n_components=3, n_neighbors=15, min_dist=.05, mask=None, min_cluster_size=5,
                    metric='cosine', projection=None, cluster_voxels=False, visualize_failed_clusters=True,
                    cols_to_flip=cols_to_flip)
umapper.run(out_dir)

[BrainUmap] Flipped 14 input map(s): ['/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/DigitSpanBackwardRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/CategorySwitchRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/PhonemicFluencyRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/GoNoGoRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/SimiliarityRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/DigitSpanForwardRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/VerbalRecallRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/SematicFluencyRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/CubeDrawRawS-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/ExecutiveTotal-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/LanguageTotal-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/MemoryTotal-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/VisualTotal-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz', '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions/VerbalRegSum-on-Nifti_File_Path/regression/contrast_tval_0.nii.gz']

[BrainUmap] Cluster report saved to: /Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/symptom_on_lhs/proper_regressions_clusters/cluster_results.csv