# 01 - Find Files

**Search for the Files**
_______
Formatting the Directory-Pattern Dictionary
The function glob_multiple_file_paths expects a dictionary where each key-value pair corresponds to a root directory and a file pattern to search within that directory. The keys are the root directories where you want to start the search, and the values are the file patterns to match against.

Example Dictionary Format:

>dir_pattern_dict = {
>    '/path/to/first/root_dir': '*.nii',
>
>    '/path/to/second/root_dir': '*.nii.gz',
>
>    '/another/path': '*_label.nii'
>     Add more key-value pairs as needed
>}

Using Wildcards:

The file patterns can include wildcards to match multiple files:
- *: Matches zero or more characters
- **: Searches all directories recursively
- *.nii will match all files ending with .nii
- ?: Matches any single character
- file?.nii will match file1.nii, file2.nii, etc.
- [seq]: Matches any character in seq
- file[1-3].nii will match file1.nii, file2.nii, file3.nii
- [!seq]: Matches any character NOT in seq
- file[!1-3].nii will match any file that doesn't have 1, 2, or 3 in that position, like file4.nii, file5.nii, etc.

Feel free to combine these wildcards to create complex file patterns. For example, *_??.nii will match files like file_01.nii, file_02.nii, etc.

Where to Save to

In [1]:
# Define the dictionary with root directories and file patterns

dir_pattern_dict = {
    "/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/sub-*/ses-*/roi/": '*-space_resampled.nii.gz'}

eventual_colname='Nifti_File_Path'

## Glob the files and check to see if acceptable

In [2]:
save_files = False

In [3]:
from calvin_utils.file_utils.file_path_collector import glob_multiple_file_paths
import os
# Validate Directory
# os.mkdir(os.path.dirname(csv_path))
# Call the function and save the returned DataFrame to a CSV file
path_df = glob_multiple_file_paths(dir_pattern_dict, save=save_files, save_path=None)

# Display the saved path and the DataFrame
display(path_df)

                                                paths
0   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
1   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
2   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
3   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
4   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
..                                                ...
64  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
65  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
66  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
67  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
68  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...

[69 rows x 1 columns]

# Option 2 - Extract Subject IDs

In [4]:
# Define the preceding and proceeding strings
preceding = 'sub-'
proceeding = '/'

# Extract the substring and add it to a new column 'subject'
path_df['subid'] = path_df['paths'].str.extract(f'{preceding}(.*?){proceeding}')

# Display the updated DataFrame
display(path_df)

                                                paths subid
0   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    13
1   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    14
2   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    22
3   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    25
4   /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    71
..                                                ...   ...
64  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    66
65  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    59
66  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    50
67  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    57
68  /Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...    68

[69 rows x 2 columns]

In [5]:
# path_df['map_ID'] = path_df['map_ID'].astype(int)

# 03 Option A - Import Another CSV and Add the Paths to It
**The CSV is expected to be in this format**
- ID and absolute paths to niftis are critical
```
+-----+----------------------------+--------------+--------------+--------------+
| ID  | Nifti_File_Path            | Covariate_1  | Covariate_2  | Covariate_3  |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 3.4          |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 3.1          |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 3.5          |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3.2          |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

In [6]:
spreadsheet_path = '/Volumes/OneTouch/01x_Dhand_RCPStrokes/metadata/master.csv'
sheet = None #If using Excel, enter a string here

In [7]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
# Instantiate the PalmPrepararation class
cal_palm = CalvinStatsmodelsPalm(input_csv_path=spreadsheet_path, output_dir=os.path.dirname(spreadsheet_path), sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,subject_id,session_id,mni_lesion_path,alternate_mni_lesion_path,ccas__Record_ID,ccas__Event_Name,ccas__SematicFluencyRawS,ccas__SematicFluencyFailS,ccas__PhonemicFluencyRawS,ccas__PhonemicFluencyFailS,...,bars__bars_left_finger_to_nose,bars__bars_right_finger_to_nose,bars__limb_ataxia,bars__bars_speech,bars__bars_oculomotor,bars__bars_observations,bars__bars_total_reported,bars__bars_total_calculated,bars__bars_feedback,bars__complete
0,sub-01,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,1,Intake,18.0,Pass,8.0,Fail,...,0.0,0.0,0.0,0.0,0.0,NaN,0.5,0.5,NaN,Complete
1,sub-02,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,2,Intake,4.0,Fail,6.0,Fail,...,0.0,0.0,0.0,0.0,0.0,NaN,7.0,7.0,NaN,Complete
2,sub-03,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,3,Intake,20.0,Pass,4.0,Fail,...,4.0,0.0,8.5,1.0,0.5,Saccadic movements slow on the left side,18.0,18.0,NaN,Complete
3,sub-04,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,4,Intake,21.0,Pass,5.0,Fail,...,0.0,1.5,1.5,0.5,0.0,NaN,8.0,8.0,NaN,Complete
4,sub-06,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,6,Intake,16.0,Pass,5.0,Fail,...,0.0,0.0,0.0,0.0,0.0,NaN,0.5,0.5,NaN,Complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,sub-85,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,85,Intake,13.0,Fail,19.0,Pass,...,0.0,0.0,0.5,0.5,0.0,NaN,1.0,1.0,Unable to complete parts of the assessment due...,Complete
78,sub-86,ses-01,NaN,NaN,86,Intake,25.0,Pass,13.0,Pass,...,1.0,0.0,1.5,0.0,0.0,NaN,2.0,2.0,NaN,Complete
79,sub-87,ses-01,NaN,NaN,87,Intake,19.0,Pass,11.0,Pass,...,0.0,0.5,0.5,1.0,0.0,NaN,6.5,6.5,NaN,Complete
80,sub-88,ses-01,NaN,NaN,88,Intake,24.0,Pass,16.0,Pass,...,0.0,0.0,0.5,0.0,0.0,NaN,1.0,1.0,NaN,Complete
81,sub-89,ses-01,NaN,NaN,89,Intake,16.0,Pass,12.0,Pass,...,0.5,0.5,3.0,0.0,0.0,"Patient has a tremor in both hands, reports th...",4.0,4.0,NaN,Complete

In [9]:
subcol = data_df["subject_id"].str.replace("sub-", "", regex=False)

data_df['subid'] = subcol

In [10]:
data_df['subid'] = data_df['subid'].astype(int)
path_df['subid'] = path_df['subid'].astype(int)

In [12]:
merged_df = data_df.merge(path_df, on='subid', how='outer', suffixes=('', '_updrstract'))
display(merged_df)

,subject_id,session_id,mni_lesion_path,alternate_mni_lesion_path,ccas__Record_ID,ccas__Event_Name,ccas__SematicFluencyRawS,ccas__SematicFluencyFailS,ccas__PhonemicFluencyRawS,ccas__PhonemicFluencyFailS,...,bars__limb_ataxia,bars__bars_speech,bars__bars_oculomotor,bars__bars_observations,bars__bars_total_reported,bars__bars_total_calculated,bars__bars_feedback,bars__complete,subid,paths
0,sub-01,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,1,Intake,18.0,Pass,8.0,Fail,...,0.0,0.0,0.0,NaN,0.5,0.5,NaN,Complete,1,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
1,sub-02,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,2,Intake,4.0,Fail,6.0,Fail,...,0.0,0.0,0.0,NaN,7.0,7.0,NaN,Complete,2,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
2,sub-03,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,3,Intake,20.0,Pass,4.0,Fail,...,8.5,1.0,0.5,Saccadic movements slow on the left side,18.0,18.0,NaN,Complete,3,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
3,sub-04,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,4,Intake,21.0,Pass,5.0,Fail,...,1.5,0.5,0.0,NaN,8.0,8.0,NaN,Complete,4,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
4,sub-06,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,6,Intake,16.0,Pass,5.0,Fail,...,0.0,0.0,0.0,NaN,0.5,0.5,NaN,Complete,6,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,sub-85,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,85,Intake,13.0,Fail,19.0,Pass,...,0.5,0.5,0.0,NaN,1.0,1.0,Unable to complete parts of the assessment due...,Complete,85,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
78,sub-86,ses-01,NaN,NaN,86,Intake,25.0,Pass,13.0,Pass,...,1.5,0.0,0.0,NaN,2.0,2.0,NaN,Complete,86,NaN
79,sub-87,ses-01,NaN,NaN,87,Intake,19.0,Pass,11.0,Pass,...,0.5,1.0,0.0,NaN,6.5,6.5,NaN,Complete,87,NaN
80,sub-88,ses-01,NaN,NaN,88,Intake,24.0,Pass,16.0,Pass,...,0.5,0.0,0.0,NaN,1.0,1.0,NaN,Complete,88,NaN
81,sub-89,ses-01,NaN,NaN,89,Intake,16.0,Pass,12.0,Pass,...,3.0,0.0,0.0,"Patient has a tremor in both hands, reports th...",4.0,4.0,NaN,Complete,89,NaN

Rename Paths Column

In [13]:
merged_df = merged_df.rename(columns={'paths': eventual_colname})
display(merged_df)

,subject_id,session_id,mni_lesion_path,alternate_mni_lesion_path,ccas__Record_ID,ccas__Event_Name,ccas__SematicFluencyRawS,ccas__SematicFluencyFailS,ccas__PhonemicFluencyRawS,ccas__PhonemicFluencyFailS,...,bars__limb_ataxia,bars__bars_speech,bars__bars_oculomotor,bars__bars_observations,bars__bars_total_reported,bars__bars_total_calculated,bars__bars_feedback,bars__complete,subid,Nifti_File_Path
0,sub-01,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,1,Intake,18.0,Pass,8.0,Fail,...,0.0,0.0,0.0,NaN,0.5,0.5,NaN,Complete,1,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
1,sub-02,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,2,Intake,4.0,Fail,6.0,Fail,...,0.0,0.0,0.0,NaN,7.0,7.0,NaN,Complete,2,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
2,sub-03,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,3,Intake,20.0,Pass,4.0,Fail,...,8.5,1.0,0.5,Saccadic movements slow on the left side,18.0,18.0,NaN,Complete,3,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
3,sub-04,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,4,Intake,21.0,Pass,5.0,Fail,...,1.5,0.5,0.0,NaN,8.0,8.0,NaN,Complete,4,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
4,sub-06,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,6,Intake,16.0,Pass,5.0,Fail,...,0.0,0.0,0.0,NaN,0.5,0.5,NaN,Complete,6,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,sub-85,ses-01,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...,NaN,85,Intake,13.0,Fail,19.0,Pass,...,0.5,0.5,0.0,NaN,1.0,1.0,Unable to complete parts of the assessment due...,Complete,85,/Volumes/OneTouch/01x_Dhand_RCPStrokes/BIDS/su...
78,sub-86,ses-01,NaN,NaN,86,Intake,25.0,Pass,13.0,Pass,...,1.5,0.0,0.0,NaN,2.0,2.0,NaN,Complete,86,NaN
79,sub-87,ses-01,NaN,NaN,87,Intake,19.0,Pass,11.0,Pass,...,0.5,1.0,0.0,NaN,6.5,6.5,NaN,Complete,87,NaN
80,sub-88,ses-01,NaN,NaN,88,Intake,24.0,Pass,16.0,Pass,...,0.5,0.0,0.0,NaN,1.0,1.0,NaN,Complete,88,NaN
81,sub-89,ses-01,NaN,NaN,89,Intake,16.0,Pass,12.0,Pass,...,3.0,0.0,0.0,"Patient has a tremor in both hands, reports th...",4.0,4.0,NaN,Complete,89,NaN

Save the merged df

In [14]:
merged_df.to_csv(spreadsheet_path, index=False)

# 03 Option B - Save Path DF To Its Own CSV

In [ ]:
# import os
# out_dir = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/memory_dbs/spreadsheets/master_vtas.csv'
# # os.makedirs(out_dir, exist_ok=True)
# path_df.to_csv(out_dir, index=False)

Hope this was helpful

--Calvin