# 01 - Find Files

**Search for the Files**
_______
Formatting the Directory-Pattern Dictionary
The function glob_multiple_file_paths expects a dictionary where each key-value pair corresponds to a root directory and a file pattern to search within that directory. The keys are the root directories where you want to start the search, and the values are the file patterns to match against.

Example Dictionary Format:

>dir_pattern_dict = {
>    '/path/to/first/root_dir': '*.nii',
>
>    '/path/to/second/root_dir': '*.nii.gz',
>
>    '/another/path': '*_label.nii'
>     Add more key-value pairs as needed
>}

Using Wildcards:

The file patterns can include wildcards to match multiple files:
- *: Matches zero or more characters
- **: Searches all directories recursively
- *.nii will match all files ending with .nii
- ?: Matches any single character
- file?.nii will match file1.nii, file2.nii, etc.
- [seq]: Matches any character in seq
- file[1-3].nii will match file1.nii, file2.nii, file3.nii
- [!seq]: Matches any character NOT in seq
- file[!1-3].nii will match any file that doesn't have 1, 2, or 3 in that position, like file4.nii, file5.nii, etc.

Feel free to combine these wildcards to create complex file patterns. For example, *_??.nii will match files like file_01.nii, file_02.nii, etc.

Where to Save to

In [130]:
# Define the dictionary with root directories and file patterns

dir_pattern_dict = {
    "/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer_DBS/subjects/sub-*/stimulations/optimized/convergent_memory_target_map-DeterministicNoProjection/electrode_right": 'vta.nii.gz'}

eventual_colname='right_geometric_vta_optimized_DeterministicNoProjection'

## Glob the files and check to see if acceptable

In [131]:
save_files = False

In [132]:
from calvin_utils.file_utils.file_path_collector import glob_multiple_file_paths
import os
# Validate Directory
# os.mkdir(os.path.dirname(csv_path))
# Call the function and save the returned DataFrame to a CSV file
path_df = glob_multiple_file_paths(dir_pattern_dict, save=save_files, save_path=None)

# Display the saved path and the DataFrame
display(path_df)

                                                paths
0   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
1   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
2   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
3   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
4   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
5   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
6   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
7   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
8   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
9   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
10  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
11  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
12  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
13  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
14  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
15  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
16  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
17  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
18  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
19  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
20  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
21  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
22  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
23  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
24  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
25  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
26  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
27  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
28  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
29  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
30  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
31  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
32  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
33  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
34  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
35  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
36  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
37  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
38  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
39  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
40  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
41  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
42  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
43  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
44  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
45  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
46  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
47  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
48  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
49  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...

# Option 2 - Extract Subject IDs

In [133]:
# Define the preceding and proceeding strings
preceding = 'subjects/sub-'
proceeding = '/'

# Extract the substring and add it to a new column 'subject'
path_df['Subject'] = path_df['paths'].str.extract(f'{preceding}(.*?){proceeding}')

# Display the updated DataFrame
display(path_df)

                                                paths Subject
0   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     101
1   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     102
2   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     103
3   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     104
4   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     105
5   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     106
6   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     107
7   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     108
8   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     109
9   /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     110
10  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     111
11  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     112
12  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     113
13  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     114
14  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     115
15  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     116
16  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     118
17  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     119
18  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     120
19  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...    1201
20  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...    1202
21  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...    1203
22  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     121
23  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     122
24  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     123
25  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     124
26  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     125
27  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     126
28  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     127
29  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     128
30  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     129
31  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     130
32  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     131
33  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     133
34  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     134
35  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     135
36  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     137
37  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     138
38  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     139
39  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     140
40  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     141
41  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     142
42  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     143
43  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     144
44  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     145
45  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     146
46  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     147
47  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     148
48  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     149
49  /Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...     150

In [134]:
# path_df['map_ID'] = path_df['map_ID'].astype(int)

# 03 Option A - Import Another CSV and Add the Paths to It
**The CSV is expected to be in this format**
- ID and absolute paths to niftis are critical
```
+-----+----------------------------+--------------+--------------+--------------+
| ID  | Nifti_File_Path            | Covariate_1  | Covariate_2  | Covariate_3  |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 3.4          |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 3.1          |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 3.5          |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3.2          |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

In [135]:
spreadsheet_path = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/memory_dbs/spreadsheets/master_list.csv'
sheet = None #If using Excel, enter a string here

In [136]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
# Instantiate the PalmPrepararation class
cal_palm = CalvinStatsmodelsPalm(input_csv_path=spreadsheet_path, output_dir=os.path.dirname(spreadsheet_path), sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,Subject,cohort,session,memory_improvement,outcome_measure,stimpyper_redo_clinical_bilateral_vta,stimpyper_redo_optimized_bilateral_vta,Age_at_DOS,PT,Month_12_Delta_ADAS11Score,...,bilateral_geometric_vta_clinician,bilateral_geometric_vta_optimal_YesProjection,right_geometric_vta_optimized_NoProjection,left_geometric_vta_optimized_NoProjection,bilateral_geometric_vta_optimized_NoProjection,left_geometric_vta_optimized_DeterministicYesProjection,left_geometric_vta_optimized_DeterministicYesProjection_1,right_geometric_vta_optimized_DeterministicYesProjection,bilateral_geometric_vta_optimized_DeterministicYesProjection,left_geometric_vta_optimized_DeterministicNoProjection
0,101,toronto,NaN,4.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,62.0,FNM01004,-11.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
1,102,toronto,NaN,6.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,77.0,FNM01007,-8.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
2,103,toronto,NaN,4.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,76.0,FNM01014,-3.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
3,104,toronto,NaN,8.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,65.0,FNM01006,-22.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
4,105,toronto,NaN,NaN,NaN,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,50.0,NaN,NaN,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,sub-0015,cologne_fornix,ses-01,-9.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,sub-0016,cologne_fornix,ses-01,-6.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,sub-0017,cologne_fornix,ses-01,0.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,sub-0019,cologne_fornix,ses-01,-13.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,sub-0020,cologne_fornix,ses-01,-3.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
data_df['Subject'] = data_df['Subject'].astype(str)
path_df['Subject'] = path_df['Subject'].astype(str)

In [138]:
merged_df = data_df.merge(path_df, on='Subject', how='outer', suffixes=('', '_updrstract'))
display(merged_df)

,Subject,cohort,session,memory_improvement,outcome_measure,stimpyper_redo_clinical_bilateral_vta,stimpyper_redo_optimized_bilateral_vta,Age_at_DOS,PT,Month_12_Delta_ADAS11Score,...,bilateral_geometric_vta_optimal_YesProjection,right_geometric_vta_optimized_NoProjection,left_geometric_vta_optimized_NoProjection,bilateral_geometric_vta_optimized_NoProjection,left_geometric_vta_optimized_DeterministicYesProjection,left_geometric_vta_optimized_DeterministicYesProjection_1,right_geometric_vta_optimized_DeterministicYesProjection,bilateral_geometric_vta_optimized_DeterministicYesProjection,left_geometric_vta_optimized_DeterministicNoProjection,paths
0,101,toronto,NaN,4.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,62.0,FNM01004,-11.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
1,102,toronto,NaN,6.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,77.0,FNM01007,-8.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
2,103,toronto,NaN,4.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,76.0,FNM01014,-3.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
3,104,toronto,NaN,8.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,65.0,FNM01006,-22.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
4,105,toronto,NaN,NaN,NaN,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,50.0,NaN,NaN,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,sub-0015,cologne_fornix,ses-01,-9.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,sub-0016,cologne_fornix,ses-01,-6.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,sub-0017,cologne_fornix,ses-01,0.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,sub-0019,cologne_fornix,ses-01,-13.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,sub-0020,cologne_fornix,ses-01,-3.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Rename Paths Column

In [139]:
merged_df = merged_df.rename(columns={'paths': eventual_colname})
display(merged_df)

,Subject,cohort,session,memory_improvement,outcome_measure,stimpyper_redo_clinical_bilateral_vta,stimpyper_redo_optimized_bilateral_vta,Age_at_DOS,PT,Month_12_Delta_ADAS11Score,...,bilateral_geometric_vta_optimal_YesProjection,right_geometric_vta_optimized_NoProjection,left_geometric_vta_optimized_NoProjection,bilateral_geometric_vta_optimized_NoProjection,left_geometric_vta_optimized_DeterministicYesProjection,left_geometric_vta_optimized_DeterministicYesProjection_1,right_geometric_vta_optimized_DeterministicYesProjection,bilateral_geometric_vta_optimized_DeterministicYesProjection,left_geometric_vta_optimized_DeterministicNoProjection,right_geometric_vta_optimized_DeterministicNoProjection
0,101,toronto,NaN,4.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,62.0,FNM01004,-11.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
1,102,toronto,NaN,6.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,77.0,FNM01007,-8.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
2,103,toronto,NaN,4.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,76.0,FNM01014,-3.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
3,104,toronto,NaN,8.0,Month_12_Delta_ADASMemImprovement,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,65.0,FNM01006,-22.0,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
4,105,toronto,NaN,NaN,NaN,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,50.0,NaN,NaN,...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...,/Volumes/HowExp/datasets/03h_ADVANCE_Alzheimer...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,sub-0015,cologne_fornix,ses-01,-9.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,sub-0016,cologne_fornix,ses-01,-6.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,sub-0017,cologne_fornix,ses-01,0.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,sub-0019,cologne_fornix,ses-01,-13.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,sub-0020,cologne_fornix,ses-01,-3.0,Improve1FUbaseline_ADAS_mem,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Users/cu135/Partners HealthCare Dropbox/Calvi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Save the merged df

In [140]:
merged_df.to_csv(spreadsheet_path, index=False)

# 03 Option B - Save Path DF To Its Own CSV

In [141]:
# import os
# out_dir = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/memory_dbs/spreadsheets/master_vtas.csv'
# # os.makedirs(out_dir, exist_ok=True)
# path_df.to_csv(out_dir, index=False)

Hope this was helpful

--Calvin