# 01 - Find Files

**Search for the Files**
_______
Formatting the Directory-Pattern Dictionary
The function glob_multiple_file_paths expects a dictionary where each key-value pair corresponds to a root directory and a file pattern to search within that directory. The keys are the root directories where you want to start the search, and the values are the file patterns to match against.

Example Dictionary Format:

>dir_pattern_dict = {
>    '/path/to/first/root_dir': '*.nii',
>
>    '/path/to/second/root_dir': '*.nii.gz',
>
>    '/another/path': '*_label.nii'
>     Add more key-value pairs as needed
>}

Using Wildcards:

The file patterns can include wildcards to match multiple files:
- *: Matches zero or more characters
- **: Searches all directories recursively
- *.nii will match all files ending with .nii
- ?: Matches any single character
- file?.nii will match file1.nii, file2.nii, etc.
- [seq]: Matches any character in seq
- file[1-3].nii will match file1.nii, file2.nii, file3.nii
- [!seq]: Matches any character NOT in seq
- file[!1-3].nii will match any file that doesn't have 1, 2, or 3 in that position, like file4.nii, file5.nii, etc.

Feel free to combine these wildcards to create complex file patterns. For example, *_??.nii will match files like file_01.nii, file_02.nii, etc.

Where to Save to

In [38]:
# Define the dictionary with root directories and file patterns

dir_pattern_dict = {
    '/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/*/ses-01/unthresholded_tissue_segment_z_scores': '*white_matter.nii.gz'}

eventual_colname='wm_atrophy_path'

## Glob the files and check to see if acceptable

In [39]:
save_files = False

In [40]:
from calvin_utils.file_utils.file_path_collector import glob_multiple_file_paths
import os
# Validate Directory
# os.mkdir(os.path.dirname(csv_path))
# Call the function and save the returned DataFrame to a CSV file
path_df = glob_multiple_file_paths(dir_pattern_dict, save=save_files, save_path=None)

# Display the saved path and the DataFrame
display(path_df)

                                                  paths
0     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
2     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
3     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
4     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...                                                 ...
1300  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1301  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1302  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1303  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1304  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...

[1305 rows x 1 columns]

# Option 2 - Extract Subject IDs

In [41]:
# Define the preceding and proceeding strings
preceding = 'sub-'
proceeding = '/'

# Extract the substring and add it to a new column 'subject'
path_df['subid'] = path_df['paths'].str.extract(f'{preceding}(.*?){proceeding}')

# Display the updated DataFrame
display(path_df)

                                                  paths       subid
0     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  002_S_0295
1     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  002_S_0413
2     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  002_S_0559
3     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  002_S_0619
4     /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  002_S_0685
...                                                 ...         ...
1300  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  941_S_4365
1301  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  941_S_4376
1302  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  941_S_4377
1303  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  941_S_4420
1304  /Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...  941_S_4764

[1305 rows x 2 columns]

In [42]:
# path_df['map_ID'] = path_df['map_ID'].astype(int)

# 03 Option A - Import Another CSV and Add the Paths to It
**The CSV is expected to be in this format**
- ID and absolute paths to niftis are critical
```
+-----+----------------------------+--------------+--------------+--------------+
| ID  | Nifti_File_Path            | Covariate_1  | Covariate_2  | Covariate_3  |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 3.4          |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 3.1          |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 3.5          |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3.2          |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

In [43]:
spreadsheet_path = '/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/metadata/cleaned_information/discovery.csv'
sheet = None #If using Excel, enter a string here

In [44]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
# Instantiate the PalmPrepararation class
cal_palm = CalvinStatsmodelsPalm(input_csv_path=spreadsheet_path, output_dir=os.path.dirname(spreadsheet_path), sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,GM_Subcortex,...,CTh_Subcortex,Q4,TOTAL11,TOTALMOD,DX_BASELINE,DX_M12,atrophy_path,subject,csf_atrophy_path,gm_atrophy_path
0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.59211,-18245.868460,-32777.02389,-23248.955500,1038.504856,...,0.0,1.0,3.00,4.00,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0295,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.97717,-6191.852471,-13476.49339,-4562.384254,6161.244622,...,0.0,1.0,3.33,4.33,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0413,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.36704,-33934.639930,-32128.02182,-7651.536038,-611.057402,...,0.0,2.0,6.00,8.00,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0559,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
3,002_S_0619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0619,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.08397,-48808.714580,-31102.25568,-7164.119248,-72582.823910,...,0.0,3.0,3.67,6.67,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0685,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1300,941_S_4365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4365,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1301,941_S_4376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4376,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1302,941_S_4377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4377,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1303,941_S_4420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4420,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1304,941_S_4764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4764,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...

In [45]:
data_df['subid'] = data_df['subid'].astype(str)
path_df['subid'] = path_df['subid'].astype(str)

In [46]:
merged_df = data_df.merge(path_df, on='subid', how='outer', suffixes=('', '_updrstract'))
display(merged_df)

,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,GM_Subcortex,...,Q4,TOTAL11,TOTALMOD,DX_BASELINE,DX_M12,atrophy_path,subject,csf_atrophy_path,gm_atrophy_path,paths
0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.59211,-18245.868460,-32777.02389,-23248.955500,1038.504856,...,1.0,3.00,4.00,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0295,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.97717,-6191.852471,-13476.49339,-4562.384254,6161.244622,...,1.0,3.33,4.33,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0413,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.36704,-33934.639930,-32128.02182,-7651.536038,-611.057402,...,2.0,6.00,8.00,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0559,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
3,002_S_0619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0619,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.08397,-48808.714580,-31102.25568,-7164.119248,-72582.823910,...,3.0,3.67,6.67,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0685,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1300,941_S_4365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4365,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1301,941_S_4376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4376,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1302,941_S_4377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4377,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1303,941_S_4420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4420,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1304,941_S_4764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4764,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...

Rename Paths Column

In [47]:
merged_df = merged_df.rename(columns={'paths': eventual_colname})
display(merged_df)

,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,GM_Subcortex,...,Q4,TOTAL11,TOTALMOD,DX_BASELINE,DX_M12,atrophy_path,subject,csf_atrophy_path,gm_atrophy_path,wm_atrophy_path
0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.59211,-18245.868460,-32777.02389,-23248.955500,1038.504856,...,1.0,3.00,4.00,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0295,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.97717,-6191.852471,-13476.49339,-4562.384254,6161.244622,...,1.0,3.33,4.33,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0413,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.36704,-33934.639930,-32128.02182,-7651.536038,-611.057402,...,2.0,6.00,8.00,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0559,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
3,002_S_0619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0619,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.08397,-48808.714580,-31102.25568,-7164.119248,-72582.823910,...,3.0,3.67,6.67,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,002_S_0685,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1300,941_S_4365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4365,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1301,941_S_4376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4376,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1302,941_S_4377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4377,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1303,941_S_4420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4420,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1304,941_S_4764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,941_S_4764,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...

Save the merged df

In [48]:
merged_df.to_csv(spreadsheet_path, index=False)

# 03 Option B - Save Path DF To Its Own CSV

In [ ]:
# import os
# out_dir = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/memory_dbs/spreadsheets/master_vtas.csv'
# # os.makedirs(out_dir, exist_ok=True)
# path_df.to_csv(out_dir, index=False)

Hope this was helpful

--Calvin