In [3]:
# Specify the path to your CSV file containing NIFTI paths
input_csv_path = '/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/metadata/cleaned_information/master.csv'
sheet = None

In [6]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
# Instantiate the PalmPrepararation class
cal_palm = CalvinStatsmodelsPalm(input_csv_path=input_csv_path, output_dir=None, sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,DX_BASELINE,DX_M12,wm_atrophy_path,gm_atrophy_path,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed
0,0,002_S_0295,-26319.38152,373.297842,-746.688684,-24081.964640,-32607.592110,-18245.868460,-32777.023890,-23248.955500,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1,1,002_S_0413,-13670.88871,5009.504947,-449.838607,-8185.340726,-13903.977170,-6191.852471,-13476.493390,-4562.384254,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
2,2,002_S_0559,-38702.13792,152.392985,-754.706246,-25738.506400,-34449.367040,-33934.639930,-32128.021820,-7651.536038,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
3,3,002_S_0619,-35472.21632,-23876.106190,-1947.061673,-51088.102680,-81475.108430,-66818.857830,-72864.628840,-30069.234640,...,Alzheimer,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
4,4,002_S_0685,-31092.93296,-22643.911490,-1014.786011,-32806.816640,-18280.083970,-48808.714580,-31102.255680,-7164.119248,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383,1383,941_S_4365,-38529.96216,-15404.929680,-662.636580,-45763.001790,-51966.135180,-50434.470830,-48981.572530,-9171.789970,...,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1384,1384,941_S_4376,-17949.11453,-104.528538,-236.251734,-30861.230910,-12256.220060,-26738.830580,-20657.277210,-21140.712780,...,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1385,1385,941_S_4377,-15992.36193,8601.241440,-63.774856,-17403.780770,-5480.603967,-8570.005333,-6582.358081,8848.744873,...,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1386,1386,941_S_4420,-16826.37025,-551.877244,-240.304833,-19856.342990,-43372.373360,-24995.432550,-31441.476020,-5076.530307,...,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1387,1387,941_S_4764,-29967.55872,-4994.645463,-611.921947,-31815.427780,-48597.166250,-30940.654970,-37860.577210,-16533.750280,...,NaN,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...


# 01 - Preprocess Your Data

**Handle NANs**
- Set drop_nans=True is you would like to remove NaNs from data
- Provide a column name or a list of column names to remove NaNs from

In [7]:
data_df.columns

Index(['Unnamed__0', 'subid', 'CSF_Cerebellum', 'CSF_Subcortex', 'CSF_MTL',
       'CSF_Occipital', 'CSF_Frontal', 'CSF_Parietal', 'CSF_Temporal',
       'GM_Cerebellum', 'GM_Subcortex', 'GM_MTL', 'GM_Occipital', 'GM_Frontal',
       'GM_Parietal', 'GM_Temporal', 'WM_Cerebellum', 'WM_Subcortex', 'WM_MTL',
       'WM_Occipital', 'WM_Frontal', 'WM_Parietal', 'WM_Temporal',
       'Visual_Frontal', 'Visual_Parietal', 'Visual_Occipital',
       'Visual_Temporal', 'Visual_Cerebellum', 'Visual_Subcortex',
       'Visual_MTL', 'Cohort', 'Diagnosis', 'Sex', 'Age', 'Cohort_1',
       'CTh_Cerebellum', 'CTh_MTL', 'CTh_Occipital', 'CTh_Frontal',
       'CTh_Parietal', 'CTh_Temporal', 'CTh_Subcortex', 'Q4', 'TOTAL11',
       'TOTALMOD', 'DX_BASELINE', 'DX_M12', 'wm_atrophy_path',
       'gm_atrophy_path', 'fluid_atrophy_path', 'composite_atrophy_path',
       'wm_atrophy_path_smoothed', 'gm_atrophy_path_smoothed',
       'fluid_atrophy_path_smoothed', 'composite_atrophy_path_smoothed'],
      dtype='object')

In [8]:
drop_list = ['DX_BASELINE', 'fluid_atrophy_path_smoothed']

In [9]:
data_df = cal_palm.drop_nans_from_columns(columns_to_drop_from=drop_list)
data_df

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,DX_BASELINE,DX_M12,wm_atrophy_path,gm_atrophy_path,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed
0,0,002_S_0295,-26319.381520,373.297842,-746.688684,-24081.964640,-32607.59211,-18245.868460,-32777.02389,-23248.955500,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1,1,002_S_0413,-13670.888710,5009.504947,-449.838607,-8185.340726,-13903.97717,-6191.852471,-13476.49339,-4562.384254,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
2,2,002_S_0559,-38702.137920,152.392985,-754.706246,-25738.506400,-34449.36704,-33934.639930,-32128.02182,-7651.536038,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
3,3,002_S_0619,-35472.216320,-23876.106190,-1947.061673,-51088.102680,-81475.10843,-66818.857830,-72864.62884,-30069.234640,...,Alzheimer,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
4,4,002_S_0685,-31092.932960,-22643.911490,-1014.786011,-32806.816640,-18280.08397,-48808.714580,-31102.25568,-7164.119248,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1372,1372,941_S_1202,-26352.604880,-735.110333,-561.225070,-9934.943656,-33858.18503,-19699.733350,-23136.85671,-43373.920500,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1373,1373,941_S_1203,-8536.033876,3546.800696,-97.105074,-17019.967590,-17954.14546,-24064.472130,-16193.06243,-20234.921810,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1374,1374,941_S_1295,-21425.028080,-7503.054536,-1148.289402,-31590.371470,-54998.17537,-35886.096130,-49273.73571,-6201.197900,...,MCI,MCI,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1375,1375,941_S_1311,-27931.833440,-18230.854220,-2041.659358,-29198.450840,-40067.35334,-33367.429880,-50108.03203,-7522.223335,...,MCI,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1376,1376,941_S_1363,-11222.463150,7845.960443,-126.311359,-11262.465490,-12984.61521,-9306.024011,-12891.26141,-1764.672556,...,MCI,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...

**Drop Row Based on Value of Column**

Define the column, condition, and value for dropping rows
- column = 'your_column_name'
- condition = 'above'  # Options: 'equal', 'above', 'below'

In [10]:
data_df.columns

Index(['Unnamed__0', 'subid', 'CSF_Cerebellum', 'CSF_Subcortex', 'CSF_MTL',
       'CSF_Occipital', 'CSF_Frontal', 'CSF_Parietal', 'CSF_Temporal',
       'GM_Cerebellum', 'GM_Subcortex', 'GM_MTL', 'GM_Occipital', 'GM_Frontal',
       'GM_Parietal', 'GM_Temporal', 'WM_Cerebellum', 'WM_Subcortex', 'WM_MTL',
       'WM_Occipital', 'WM_Frontal', 'WM_Parietal', 'WM_Temporal',
       'Visual_Frontal', 'Visual_Parietal', 'Visual_Occipital',
       'Visual_Temporal', 'Visual_Cerebellum', 'Visual_Subcortex',
       'Visual_MTL', 'Cohort', 'Diagnosis', 'Sex', 'Age', 'Cohort_1',
       'CTh_Cerebellum', 'CTh_MTL', 'CTh_Occipital', 'CTh_Frontal',
       'CTh_Parietal', 'CTh_Temporal', 'CTh_Subcortex', 'Q4', 'TOTAL11',
       'TOTALMOD', 'DX_BASELINE', 'DX_M12', 'wm_atrophy_path',
       'gm_atrophy_path', 'fluid_atrophy_path', 'composite_atrophy_path',
       'wm_atrophy_path_smoothed', 'gm_atrophy_path_smoothed',
       'fluid_atrophy_path_smoothed', 'composite_atrophy_path_smoothed'],
      dtype='object')

Set the parameters for dropping rows

In [11]:
column = 'Cohort'  # The column you'd like to evaluate
condition = 'not'  # The condition to check ('equal', 'above', 'below', 'not')
value = 'Validation' # The value to drop if found

In [12]:
data_df, other_df = cal_palm.drop_rows_based_on_value(column, condition, value)
display(data_df)

,Unnamed__0,subid,CSF_Cerebellum,CSF_Subcortex,CSF_MTL,CSF_Occipital,CSF_Frontal,CSF_Parietal,CSF_Temporal,GM_Cerebellum,...,DX_BASELINE,DX_M12,wm_atrophy_path,gm_atrophy_path,fluid_atrophy_path,composite_atrophy_path,wm_atrophy_path_smoothed,gm_atrophy_path_smoothed,fluid_atrophy_path_smoothed,composite_atrophy_path_smoothed
3,3,002_S_0619,-35472.216320,-23876.106190,-1947.061673,-51088.10268,-81475.108430,-66818.857830,-72864.62884,-30069.234640,...,Alzheimer,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
10,10,002_S_0955,-27460.228880,-4223.645647,-1808.785280,-42136.37844,-25613.171140,-35525.697180,-43909.67109,13848.402800,...,Alzheimer,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
11,11,002_S_1018,-12574.755940,8513.644987,-94.284543,-14372.23896,-8599.629407,-15706.835180,-15822.41804,-28282.455710,...,Alzheimer,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
40,40,003_S_1059,-24108.470640,-10781.314700,-1600.680328,-32977.62286,-33980.868420,-42764.547270,-43597.03495,16817.200220,...,Alzheimer,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
43,43,003_S_1257,-39850.785370,-51587.474810,-4405.871162,-56695.38195,-59945.585440,-57934.726150,-75261.59588,-21115.447460,...,Alzheimer,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371,1371,941_S_1197,-13872.558410,4601.684568,-458.421924,-16817.12255,-21263.165420,-23822.893740,-23093.12069,4174.322515,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1373,1373,941_S_1203,-8536.033876,3546.800696,-97.105074,-17019.96759,-17954.145460,-24064.472130,-16193.06243,-20234.921810,...,Normal,Normal,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1374,1374,941_S_1295,-21425.028080,-7503.054536,-1148.289402,-31590.37147,-54998.175370,-35886.096130,-49273.73571,-6201.197900,...,MCI,MCI,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1375,1375,941_S_1311,-27931.833440,-18230.854220,-2041.659358,-29198.45084,-40067.353340,-33367.429880,-50108.03203,-7522.223335,...,MCI,Alzheimer,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...
1376,1376,941_S_1363,-11222.463150,7845.960443,-126.311359,-11262.46549,-12984.615210,-9306.024011,-12891.26141,-1764.672556,...,MCI,NaN,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_At...

This is the Glob-style path to the subfolder containing niftis of interest
- For example, from the base_directory, */tissue_segment_z_scores will look for all subjects, all session folders within subjects, and then check the tissue_segment_z_scores folder.

In [13]:
path = '/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/metadata/cleaned_information/master.csv'
file_pattern = None
file_column = 'composite_atrophy_path_smoothed' #'roi_path'

In [14]:
from calvin_utils.file_utils.import_functions import GiiNiiFileImport
dv_df = GiiNiiFileImport(import_path=data_df['composite_atrophy_path_smoothed'], file_pattern=file_pattern, file_column=file_column, process_special_values=True).run()
dv_df

Attempting to import from pandas series. Will fail unless a series is provided using df["path_column"]

Importing niftis: 100%|██████████| 561/561 [00:22<00:00, 25.36it/s]

,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-002_S_0619/ses-01/unthresholded_tissue_segment_z_scores/sub-002_S_0619_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-002_S_0955/ses-01/unthresholded_tissue_segment_z_scores/sub-002_S_0955_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-002_S_1018/ses-01/unthresholded_tissue_segment_z_scores/sub-002_S_1018_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-003_S_1059/ses-01/unthresholded_tissue_segment_z_scores/sub-003_S_1059_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-003_S_1257/ses-01/unthresholded_tissue_segment_z_scores/sub-003_S_1257_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-005_S_0221/ses-01/unthresholded_tissue_segment_z_scores/sub-005_S_0221_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-005_S_0814/ses-01/unthresholded_tissue_segment_z_scores/sub-005_S_0814_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-005_S_1341/ses-01/unthresholded_tissue_segment_z_scores/sub-005_S_1341_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-006_S_0653/ses-01/unthresholded_tissue_segment_z_scores/sub-006_S_0653_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-007_S_0316/ses-01/unthresholded_tissue_segment_z_scores/sub-007_S_0316_ses-01_composite_fwhm4.nii.gz,...,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-141_S_1245/ses-01/unthresholded_tissue_segment_z_scores/sub-141_S_1245_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-141_S_1255/ses-01/unthresholded_tissue_segment_z_scores/sub-141_S_1255_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-141_S_1378/ses-01/unthresholded_tissue_segment_z_scores/sub-141_S_1378_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1194/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1194_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1195/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1195_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1197/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1197_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1203/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1203_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1295/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1295_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1311/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1311_ses-01_composite_fwhm4.nii.gz,/Volumes/HowExp/datasets/01a_ADNI_Alzheimer_Atrophy/neuroimaging/all_patients/sub-941_S_1363/ses-01/unthresholded_tissue_segment_z_scores/sub-941_S_1363_ses-01_composite_fwhm4.nii.gz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**Extract Subject ID From File Names**
Using the example filenames that have been printed above, please define a general string:
1) Preceding the subject ID.
2) Proceeding the subject ID.

This Should Often Be Left Default

In [15]:
preceding_id = '/sub-'
proceeding_id = '/'

In [16]:
from calvin_utils.file_utils.import_functions import GiiNiiFileImport
dv_df = GiiNiiFileImport.splice_colnames(dv_df, preceding_id, proceeding_id)
dv_df

,002_S_0619,002_S_0955,002_S_1018,003_S_1059,003_S_1257,005_S_0221,005_S_0814,005_S_1341,006_S_0653,007_S_0316,...,141_S_1245,141_S_1255,141_S_1378,941_S_1194,941_S_1195,941_S_1197,941_S_1203,941_S_1295,941_S_1311,941_S_1363
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Load Map to Check Damage Within

Import Region of Interest Masks

In [17]:
base_directory = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0'
shared_glob_pattern = 'prediction*.nii*'

In [20]:
from calvin_utils.file_utils.import_functions import GiiNiiFileImport
iv_df = GiiNiiFileImport(import_path=base_directory, file_pattern=shared_glob_pattern).run()
iv_df

Attempting to import from: /Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction*.nii*

Importing niftis: 100%|██████████| 561/561 [00:09<00:00, 56.53it/s]

,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_222.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_473.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_322.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_195.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_85.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_510.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_241.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_410.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_341.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_9.nii.gz,...,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_540.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_211.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_260.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_531.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_360.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_431.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_203.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_552.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_303.nii.gz,/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/atrophy_seeds_2023/Figures/supplement_validation_diagnostic/voxelwise/composite/test_predictions/regression_0/prediction_452.nii.gz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
preceding_id = "prediction_"
proceeding_id = '.nii'
from calvin_utils.file_utils.import_functions import GiiNiiFileImport
iv_df = GiiNiiFileImport.splice_colnames(iv_df, preceding_id, proceeding_id)
iv_df

,222,473,322,195,85,510,241,410,341,9,...,540,211,260,531,360,431,203,552,303,452
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902625,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902626,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
902628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Extract Damage Scores Per Region of Interest

In [24]:
mask_path = '/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/resources/MNI152_T1_2mm_brain_mask.nii'

In [25]:
from calvin_utils.neuroimaging_utils.nifti_utils.damage_score_utils import DamageScorer
damage_scorer = DamageScorer(mask_path, dv_df, iv_df)
dmg_df = damage_scorer.calculate_damage_scores('dice', trace=True)
dmg_df = damage_scorer.sort_dataframes_by_index(dmg_df)
dmg_df

0it [00:00, ?it/s]

561it [00:06, 92.75it/s]

            diagonal
subject
002_S_0619  0.639075
002_S_0955  0.893822
002_S_1018  1.067055
003_S_1059  0.995404
003_S_1257  0.975079
...              ...
941_S_1197  1.065115
941_S_1203  1.133372
941_S_1295  0.607154
941_S_1311  0.699197
941_S_1363  1.139180

[561 rows x 1 columns]

Rename Column in Damage DF

In [ ]:
# dmg_df = dmg_df.rename_axis('path').reset_index()
# dmg_df = dmg_df.rename(columns={dmg_df.columns[0]: 'Subject'})
# dmg_df

Save the Results

In [ ]:
# out_path = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/resources/datasets/DBS_studies_influencing_memory/metadata/master_list2.csv'

In [ ]:
# dmg_df.to_csv(out_path)

Save Results into Master CSV

In [ ]:
master_path = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/resources/datasets/05c_Howard_MetaAlzheimerReview_DBS-TMS_Coordinates/metadata/master_list2.xlsx'
sheet = 'Sheet1'

In [ ]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
cal_palm = CalvinStatsmodelsPalm(input_csv_path=master_path, output_dir=None, sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

In [ ]:
# Perform an outer join on dmg_df and data_df using the 'path' column
merged_df = data_df.merge(dmg_df, on='subject', how='outer')
merged_df

In [ ]:
merged_df.to_excel('/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/resources/datasets/05c_Howard_MetaAlzheimerReview_DBS-TMS_Coordinates/metadata/master_list2.xlsx', index=False)

In [ ]:
master_path

# Correlation Using Those Damage Scores

In [ ]:
dmg_df.columns

In [ ]:
x_col = 'diagonal'
y_col = 'Percent_Cognitive_Improvement'

In [ ]:
from calvin_utils.statistical_utils.scatterplot import simple_scatter
simple_scatter(merged_df, x_col, y_col, '', 
               x_label="Overlap With Target Network",
               y_label="Cog improve",
               out_dir=None, 
               flip_axes=False)

All done. Enjoy your analyses. 

--Calvin