# 00 - Import CSV with All Data
**The CSV is expected to be in this format**
- ID and absolute paths to niftis are critical
```
+-----+----------------------------+--------------+--------------+--------------+
| ID  | Nifti_File_Path            | Covariate_1  | Covariate_2  | Covariate_3  |
+-----+----------------------------+--------------+--------------+--------------+
| 1   | /path/to/file1.nii.gz      | 0.5          | 1.2          | 3.4          |
| 2   | /path/to/file2.nii.gz      | 0.7          | 1.4          | 3.1          |
| 3   | /path/to/file3.nii.gz      | 0.6          | 1.5          | 3.5          |
| 4   | /path/to/file4.nii.gz      | 0.9          | 1.1          | 3.2          |
| ... | ...                        | ...          | ...          | ...          |
+-----+----------------------------+--------------+--------------+--------------+
```

Import Data

In [1]:
# Specify the path to your CSV file containing NIFTI paths
input_csv_path = '/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/results/optimzation/optimized_master_list_fibfiltered.csv'
sheet = None

In [2]:
from calvin_utils.permutation_analysis_utils.statsmodels_palm import CalvinStatsmodelsPalm
# Instantiate the PalmPrepararation class
cal_palm = CalvinStatsmodelsPalm(input_csv_path=input_csv_path, output_dir=None, sheet=sheet)
# Call the process_nifti_paths method
data_df = cal_palm.read_and_display_data()
data_df

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs,hcp_fiber_profile_path
0,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
1,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6930044,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
2,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1355923,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-103,HA-01-103-7301,SCA27B,T1_MPRAGE_SAG,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
3,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1406279,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1539729,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
5,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16067027,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
6,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16721995,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
7,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,20508602,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
8,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2071224,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-099,HA-01-099-7301,SCA27B,15_Sag_T1_3D_MP_PR_Cor_MPR,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
9,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2368336,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-002,HA-01-002-7301,SCA6,C__Cor_T1_3D,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
10,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2369031,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-091,HA-01-091-7301,SCA27B,MPR_Coronal_Ref___Revised_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
11,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,315616,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
12,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3241194,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-089,HA-01-089-7301,SCA27B,27_Sag_T1_3D_MP_mitigation,...,0.0,-2.0,-7.0,-10.0,-17.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
13,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,40396335,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
14,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,43218874,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
15,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4392765,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-105,HA-01-105-7301,SCA27B,Sag_T1_3D_MPRAG_MPR_Ax_MPR,...,0.0,-3.0,-7.0,-1.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
16,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4401431,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-051,HA-01-051-7301,SCA6,Sag_T1_3D_MPRAG_mitigation,...,-4.0,-4.0,-18.0,-16.0,-34.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
17,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4530107,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-010,HA-01-010-7301,SCA2,COR_MPR_PRE,...,-1.0,-1.0,-3.0,-9.0,-12.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
18,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4552969,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-019,HA-01-019-7301,SCA1,_MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
19,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4681221,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
20,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4722004,C__Ax_3D_VIBE,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-006,HA-01-006-7301,SCA3,C__Cor_T1_FS,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
21,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4783569,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-015,HA-01-015-7301,SCA3,Post_t1_SAG_MPRAGE,...,-6.0,-5.0,-11.0,-16.0,-27.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
22,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4792757,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-031,HA-01-031-7301,SCA1,AXIAL_MPRAGE_RECONS,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
23,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5180657,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-032,HA-01-032-7301,SCA6,501__T2_Sag_3D_Brain_VIEW,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
24,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5199392,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-076,HA-01-076-7301,SCA3,PRE_Cor_T1_3D_Bravo_MPR,...,-4.0,-2.0,-12.0,-10.0,-22.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
25,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5390756,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-047,HA-01-047-7301,SCA6/8,6__Sag_T1,...,0.0,0.0,-3.0,-1.0,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
26,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5410367,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-034,HA-01-034-7301,SCA1,COR_MPRAGE_REFORM,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
27,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5709549,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-039,HA-01-039-7301,SCA3,3d_Sag_T1,...,-3.0,-3.0,-10.0,-9.0,-19.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
28,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5737974,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-046,HA-01-046-7301,SCA3,T1_TSE_AXIAL_3MM,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
29,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5766687,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-087,HA-01-087-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
30,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5997510,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-093,HA-01-093-7301,SCA27B,MPR_Ob_Cor_A____1_0_th_1_0,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
31,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6038408,9,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-098,HA-01-098-7301,SCA27B,COR_T1_MPR,...,-4.0,-2.0,-9.0,-7.0,-16.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
32,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6227801,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-055,HA-01-055-7301,SCA2,PRE_SAG_3D_T1_MPR,...,-1.0,-7.0,-9.0,-14.0,-23.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
33,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6241170,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-085,HA-01-085-7301,SCA27B,12_Post_3D_Ax_T1_BRAVO,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
34,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6350474,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-108,HA-01-108-7301,CANVAS,SAG_T1_FS_Space_ost_MPR_AX,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
35,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6646073,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-092,HA-01-092-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
36,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6803502,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-069,HA-01-069-7301,SCA8,AX_T1,...,-2.0,-1.0,-6.0,-3.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
37,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7543232,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-077,HA-01-077-7301,CANVAS,AX_MPRAGE_T1_PO_0mm__2_0mm,...,0.0,-2.0,-17.0,-11.0,-28.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
38,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7610044,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-084,HA-01-084-7301,SCA27B,Sag_T1_3D_MPRAGE_Wave,...,-2.0,0.0,-2.0,-3.0,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
39,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7622589,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-057,HA-01-057-7301,SCA3,10_Ax_T1,...,0.0,0.0,-2.0,0.0,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
40,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7665334,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
41,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7749218,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-110,HA-01-110-7301,SCA27B,C__SAG_MPR,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
42,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7871300,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-066,HA-01-066-7301,SCA1,VI_Axial_T1_FSE_11,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
43,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7890257,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-072,HA-01-072-7301,SCA1,100___MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
44,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7997058,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-059,HA-01-059-7301,SCA6,COR_T1_POST_MPR,...,0.0,-1.0,-2.0,-6.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
45,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8231339,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-111,HA-01-111-7301,SCA27B,2__Sag_T1_3D_Mprage_Promo,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...


# 01 - Preprocess Your Data

**Handle NANs**
- Set drop_nans=True is you would like to remove NaNs from data
- Provide a column name or a list of column names to remove NaNs from

In [3]:
data_df.columns

Index(['paths', 'Nifti_File_Path', 'subid', 'session', 'selected',
       'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type',
       ...
       'TotalSection4Score', 'TotalSection5Score', 'CNRSTotColAScore',
       'CNRSTotColBScore', 'CNRSTotScore', 'roi_path', 'conn_path', 'dataset',
       'oatgs', 'hcp_fiber_profile_path'],
      dtype='object', length=119)

In [4]:
drop_list = ['selected_Nifti_File_Path']

In [5]:
data_df = cal_palm.drop_nans_from_columns(columns_to_drop_from=drop_list)
data_df

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs,hcp_fiber_profile_path
0,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
1,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6930044,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
2,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1355923,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-103,HA-01-103-7301,SCA27B,T1_MPRAGE_SAG,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
3,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1406279,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1539729,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
5,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16067027,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
6,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16721995,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
7,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,20508602,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
8,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2071224,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-099,HA-01-099-7301,SCA27B,15_Sag_T1_3D_MP_PR_Cor_MPR,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
9,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2368336,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-002,HA-01-002-7301,SCA6,C__Cor_T1_3D,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
10,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2369031,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-091,HA-01-091-7301,SCA27B,MPR_Coronal_Ref___Revised_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
11,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,315616,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
12,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3241194,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-089,HA-01-089-7301,SCA27B,27_Sag_T1_3D_MP_mitigation,...,0.0,-2.0,-7.0,-10.0,-17.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
13,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,40396335,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
14,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,43218874,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
15,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4392765,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-105,HA-01-105-7301,SCA27B,Sag_T1_3D_MPRAG_MPR_Ax_MPR,...,0.0,-3.0,-7.0,-1.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
16,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4401431,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-051,HA-01-051-7301,SCA6,Sag_T1_3D_MPRAG_mitigation,...,-4.0,-4.0,-18.0,-16.0,-34.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
17,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4530107,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-010,HA-01-010-7301,SCA2,COR_MPR_PRE,...,-1.0,-1.0,-3.0,-9.0,-12.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
18,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4552969,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-019,HA-01-019-7301,SCA1,_MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
19,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4681221,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
20,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4722004,C__Ax_3D_VIBE,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-006,HA-01-006-7301,SCA3,C__Cor_T1_FS,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
21,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4783569,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-015,HA-01-015-7301,SCA3,Post_t1_SAG_MPRAGE,...,-6.0,-5.0,-11.0,-16.0,-27.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
22,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4792757,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-031,HA-01-031-7301,SCA1,AXIAL_MPRAGE_RECONS,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
23,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5180657,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-032,HA-01-032-7301,SCA6,501__T2_Sag_3D_Brain_VIEW,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
24,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5199392,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-076,HA-01-076-7301,SCA3,PRE_Cor_T1_3D_Bravo_MPR,...,-4.0,-2.0,-12.0,-10.0,-22.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
25,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5390756,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-047,HA-01-047-7301,SCA6/8,6__Sag_T1,...,0.0,0.0,-3.0,-1.0,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
26,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5410367,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-034,HA-01-034-7301,SCA1,COR_MPRAGE_REFORM,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
27,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5709549,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-039,HA-01-039-7301,SCA3,3d_Sag_T1,...,-3.0,-3.0,-10.0,-9.0,-19.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
28,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5737974,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-046,HA-01-046-7301,SCA3,T1_TSE_AXIAL_3MM,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
29,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5766687,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-087,HA-01-087-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
30,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5997510,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-093,HA-01-093-7301,SCA27B,MPR_Ob_Cor_A____1_0_th_1_0,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
31,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6038408,9,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-098,HA-01-098-7301,SCA27B,COR_T1_MPR,...,-4.0,-2.0,-9.0,-7.0,-16.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
32,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6227801,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-055,HA-01-055-7301,SCA2,PRE_SAG_3D_T1_MPR,...,-1.0,-7.0,-9.0,-14.0,-23.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
33,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6241170,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-085,HA-01-085-7301,SCA27B,12_Post_3D_Ax_T1_BRAVO,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
34,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6350474,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-108,HA-01-108-7301,CANVAS,SAG_T1_FS_Space_ost_MPR_AX,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
35,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6646073,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-092,HA-01-092-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
36,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6803502,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-069,HA-01-069-7301,SCA8,AX_T1,...,-2.0,-1.0,-6.0,-3.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
37,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7543232,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-077,HA-01-077-7301,CANVAS,AX_MPRAGE_T1_PO_0mm__2_0mm,...,0.0,-2.0,-17.0,-11.0,-28.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
38,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7610044,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-084,HA-01-084-7301,SCA27B,Sag_T1_3D_MPRAGE_Wave,...,-2.0,0.0,-2.0,-3.0,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
39,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7622589,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-057,HA-01-057-7301,SCA3,10_Ax_T1,...,0.0,0.0,-2.0,0.0,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
40,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7665334,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
41,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7749218,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-110,HA-01-110-7301,SCA27B,C__SAG_MPR,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
42,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7871300,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-066,HA-01-066-7301,SCA1,VI_Axial_T1_FSE_11,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
43,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7890257,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-072,HA-01-072-7301,SCA1,100___MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
44,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7997058,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-059,HA-01-059-7301,SCA6,COR_T1_POST_MPR,...,0.0,-1.0,-2.0,-6.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
45,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8231339,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-111,HA-01-111-7301,SCA27B,2__Sag_T1_3D_Mprage_Promo,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...

**Drop Row Based on Value of Column**

Define the column, condition, and value for dropping rows
- column = 'your_column_name'
- condition = 'above'  # Options: 'equal', 'above', 'below'

In [6]:
data_df.columns

Index(['paths', 'Nifti_File_Path', 'subid', 'session', 'selected',
       'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type',
       ...
       'TotalSection4Score', 'TotalSection5Score', 'CNRSTotColAScore',
       'CNRSTotColBScore', 'CNRSTotScore', 'roi_path', 'conn_path', 'dataset',
       'oatgs', 'hcp_fiber_profile_path'],
      dtype='object', length=119)

Set the parameters for dropping rows

In [7]:
column = 'selected'  # The column you'd like to evaluate
condition = 'not'  # The condition to check ('equal', 'above', 'below', 'not')
value = 1 # The value to drop if found

In [8]:
data_df, other_df = cal_palm.drop_rows_based_on_value(column, condition, value)
display(data_df)

,paths,Nifti_File_Path,subid,session,selected,selected_Nifti_File_Path,id,local_id,diagnosis,scan_type,...,TotalSection4Score,TotalSection5Score,CNRSTotColAScore,CNRSTotColBScore,CNRSTotScore,roi_path,conn_path,dataset,oatgs,hcp_fiber_profile_path
0,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,272562,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
1,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6930044,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
2,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1355923,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-103,HA-01-103-7301,SCA27B,T1_MPRAGE_SAG,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
3,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1406279,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
4,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,1539729,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
5,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16067027,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
6,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,16721995,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
7,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,20508602,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
8,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2071224,7,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-099,HA-01-099-7301,SCA27B,15_Sag_T1_3D_MP_PR_Cor_MPR,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
9,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2368336,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-002,HA-01-002-7301,SCA6,C__Cor_T1_3D,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
10,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,2369031,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-091,HA-01-091-7301,SCA27B,MPR_Coronal_Ref___Revised_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
11,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,315616,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
12,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,3241194,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-089,HA-01-089-7301,SCA27B,27_Sag_T1_3D_MP_mitigation,...,0.0,-2.0,-7.0,-10.0,-17.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
13,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,40396335,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
14,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,43218874,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
15,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4392765,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-105,HA-01-105-7301,SCA27B,Sag_T1_3D_MPRAG_MPR_Ax_MPR,...,0.0,-3.0,-7.0,-1.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
16,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4401431,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-051,HA-01-051-7301,SCA6,Sag_T1_3D_MPRAG_mitigation,...,-4.0,-4.0,-18.0,-16.0,-34.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
17,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4530107,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-010,HA-01-010-7301,SCA2,COR_MPR_PRE,...,-1.0,-1.0,-3.0,-9.0,-12.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
18,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4552969,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-019,HA-01-019-7301,SCA1,_MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
19,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4681221,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
20,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4722004,C__Ax_3D_VIBE,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-006,HA-01-006-7301,SCA3,C__Cor_T1_FS,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
21,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4783569,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-015,HA-01-015-7301,SCA3,Post_t1_SAG_MPRAGE,...,-6.0,-5.0,-11.0,-16.0,-27.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
22,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,4792757,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-031,HA-01-031-7301,SCA1,AXIAL_MPRAGE_RECONS,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
23,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5180657,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-032,HA-01-032-7301,SCA6,501__T2_Sag_3D_Brain_VIEW,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
24,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5199392,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-076,HA-01-076-7301,SCA3,PRE_Cor_T1_3D_Bravo_MPR,...,-4.0,-2.0,-12.0,-10.0,-22.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
25,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5390756,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-047,HA-01-047-7301,SCA6/8,6__Sag_T1,...,0.0,0.0,-3.0,-1.0,-4.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
26,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5410367,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-034,HA-01-034-7301,SCA1,COR_MPRAGE_REFORM,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
27,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5709549,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-039,HA-01-039-7301,SCA3,3d_Sag_T1,...,-3.0,-3.0,-10.0,-9.0,-19.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
28,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5737974,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-046,HA-01-046-7301,SCA3,T1_TSE_AXIAL_3MM,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
29,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5766687,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-087,HA-01-087-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
30,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,5997510,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-093,HA-01-093-7301,SCA27B,MPR_Ob_Cor_A____1_0_th_1_0,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
31,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6038408,9,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-098,HA-01-098-7301,SCA27B,COR_T1_MPR,...,-4.0,-2.0,-9.0,-7.0,-16.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
32,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6227801,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-055,HA-01-055-7301,SCA2,PRE_SAG_3D_T1_MPR,...,-1.0,-7.0,-9.0,-14.0,-23.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
33,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6241170,4,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-085,HA-01-085-7301,SCA27B,12_Post_3D_Ax_T1_BRAVO,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
34,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6350474,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-108,HA-01-108-7301,CANVAS,SAG_T1_FS_Space_ost_MPR_AX,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
35,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6646073,3,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-092,HA-01-092-7301,SCA27B,Sag_T1,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
36,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,6803502,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-069,HA-01-069-7301,SCA8,AX_T1,...,-2.0,-1.0,-6.0,-3.0,-9.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
37,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7543232,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-077,HA-01-077-7301,CANVAS,AX_MPRAGE_T1_PO_0mm__2_0mm,...,0.0,-2.0,-17.0,-11.0,-28.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
38,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7610044,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-084,HA-01-084-7301,SCA27B,Sag_T1_3D_MPRAGE_Wave,...,-2.0,0.0,-2.0,-3.0,-5.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
39,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7622589,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-057,HA-01-057-7301,SCA3,10_Ax_T1,...,0.0,0.0,-2.0,0.0,-2.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
40,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7665334,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
41,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7749218,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-110,HA-01-110-7301,SCA27B,C__SAG_MPR,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
42,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7871300,1,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-066,HA-01-066-7301,SCA1,VI_Axial_T1_FSE_11,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
43,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7890257,5,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-072,HA-01-072-7301,SCA1,100___MPR_Range_,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
44,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,7997058,2,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-059,HA-01-059-7301,SCA6,COR_T1_POST_MPR,...,0.0,-1.0,-2.0,-6.0,-8.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...
45,/Volumes/HowExp/datasets/01p_Schmahmann_SCA_At...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,8231339,6,1,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...,HA-01-111,HA-01-111-7301,SCA27B,2__Sag_T1_3D_Mprage_Promo,...,0.0,0.0,0.0,0.0,0.0,/Users/cu135/Partners HealthCare Dropbox/Calvi...,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,NAF,/Volumes/NIMLAB/dl_archive/Atrophy_Howard/01p_...,/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/S...

# 02 - Run fiber filtering
- nifti_col - this is the column in the dataframe you provided with all the seed files in it
- patient_id_col - column in dataframe with patient ids in them
- fiber_atlas_path - the path to the atlas generated in notebook 00, or a .tt.ck from DSI Studio
- reference_nifti_path - this is the mask, typically the mask representing the space your seed niftis are in (i.e. MNI152.nii.gz)
- mode - determines how fibers are filtered. binary sets fibers to 1 if anything hits them. Max sets them to max value of what hit them. mean is the average. Read docs for more. 
- binarize - binarizes the input images
- threshold - numeric value provided if binarize=True

In [9]:
data_df.columns

Index(['paths', 'Nifti_File_Path', 'subid', 'session', 'selected',
       'selected_Nifti_File_Path', 'id', 'local_id', 'diagnosis', 'scan_type',
       ...
       'TotalSection4Score', 'TotalSection5Score', 'CNRSTotColAScore',
       'CNRSTotColBScore', 'CNRSTotScore', 'roi_path', 'conn_path', 'dataset',
       'oatgs', 'hcp_fiber_profile_path'],
      dtype='object', length=119)

In [11]:
from calvin_utils.neuroimaging_utils.tract_utils.filter_fibers import filter_fibers

runner = filter_fibers(
    df=data_df,
    nifti_col="Nifti_File_Path",
    patient_id_col="subid",  # optional, remove if not available
    fiber_atlas_path="/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/connectomic/um1_fibers.npz",
    reference_nifti_path="/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/resources/mni_icbm152_t1_tal_nlin_sym_09c_mask.nii",
    out_dir="/Volumes/OneTouch/01p_Schmahmann_SCA_Atrophy/Schmahmann_BIDS",
    mode="max",
    binarize=False,
    threshold=None
)

updated_df = runner.run()

Indexing fibers into voxel space: 100%|██████████| 176656/176656 [29:44<00:00, 98.99it/s]

Filtering patient fibers:   0%|          | 0/59 [00:00<?, ?patient/s]

/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: From release 0.13.0 onwards, this function will, by default, copy the header of the input image to the output. Currently, the header is reset to the default Nifti1Header. To suppress this warning and use the new behavior, set `copy_header=True`.
  img = image.resample_to_img(
/Users/cu135/Software_Local/calvin_utils_project/circuit_pyper/calvin_utils/neuroimaging_utils/tract_utils/compute_connectivity.py:61: FutureWarning: 'force_resample' will be set to 'True' by default in Nilearn 0.13.0.
Use 'force_resample=True' to suppress this warning.
  img = image.resample_to_img(

Save the CSV with fiber paths added to it

In [12]:
from pathlib import Path
p = Path(input_csv_path)
out_path = p.with_name(f"{p.stem}_um1fibfiltered.csv")
updated_df.to_csv(out_path, index=False)